.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature_request.md
This commit adds issue templates for
bug reports and feature requests.
=> add github issue templates

internal/log/audit.go
This commit fixes a bug in the `AuditResponseWriter`
in combination with the /v1/log/audit/trace API.
The bug is caused by calling the `ResponseWriter.WriteHeader`
method twice.
This happens when a client hits the /v1/log/audit/trace
API which adds the `http.ResponseWriter` (which is a
`AuditResponseWriter`) to the list of log output dest.
Now, when the handler function tries to write 200 OK
to the client it calls `WriteHeader` - which sends the
audit log event to all destinations (including the client
which triggers an implicit 200 OK). Then the `WriteHeader`
method actually tries write a status code to the client -
which has been done already by the logger.
This commit fixes this by having two state variables which
ensures that as soon as a implicit write happens no further …
=> avoid calling ResponseWriter.WriteHeader twice

internal/aws/secrets-manager.go
This commit fixes a bug affecting the AWS SecretsManager
key store.
When no access key, secret key or session token is provided
the credentials passed to the AWS SDK should be `nil`. This
causes the AWS SDK to look for credentials in AWS env. variables,
or EC2 metadata.
I've verified that this commit fixes the bug reported in #26 by
creating an AWS EC2 instance and specifying no credentials in the
config file.
If the correct role (e.g. SecretsManager Read/Write) is attached to
the instance specifying no credentials causes the kes server (via AWS
SDK) to fetch the temp. credentials from the EC2 metadata.
Fixes #26
=> ignore empty static credentials

CREDITS
generated using https://github.com/harshavardhana/gocredits/releases
=> add credits file for dependent libraries

cmd/kes/config.go
This commit adds support for config file templates such
that an identity in the config file can be overwritten by
a config file:
```yaml
root: ${ROOT_ID}
policy:
my-policy:
paths:
- /v1/key/create/my-key
identities:
- 6d56ee07446b7f11ad3b52d3cfd90942ad636c01288d3652a29fa0647919a3b2
- ${MY_APP_ID}
```
The above config snippet would compile to an actual config where
the root identity would be replaced by the $ROOT_ID env. variable.
Similarly, there would be two identities assigned to the `my-policy`
policy:
- 6d56ee07446b7f11ad3b52d3cfd90942ad636c01288d3652a29fa0647919a3b2
- The value of $MY_APP_ID
This templating approach has some adv. compared to allowing overwriting
arbitrary config file entries:
- A user/admin providing the config file can control what can be
customized by an executing …
=> add support for config file identity templates

internal/vault/vault.go
This commit changes the errors returned to
the KES client when KES fails to create,
get or delete a master key for some (unexpected)
reason.
Before this commit, the KES server returned errors
that happened between KES and Vault to the client.
This had two downsides:
- The client could become aware of what KMS/key store
the KES server is using.
- The client may encounter Vault-specific error messages.
Now, the KES server returns always the same `Bad Gateway` error
with a generic error message indicating that the communication between
the KES server and its KMS failed for some reason.
This behavior is already implemented by the Gemalto KeySecure
integration.
=> vault: unify errors returned to client

internal/aws/secrets-manager.go
This commit changes the errors returned to
the KES client when KES fails to create,
get or delete a master key for some (unexpected)
reason.
Before this commit, the KES server returned errors
that happened between KES and AWS Secrets Manager to
the client. This had two downsides:
- The client could become aware of what KMS/key store
the KES server is using.
- The client may encounter AWS-specific error messages.
Now, the KES server returns always the same Bad Gateway error
with a generic error message indicating that the communication between
the KES server and its KMS failed for some reason.
This behavior is already implemented by the Gemalto KeySecure
integration.
=> aws: unify errors returned to client

internal/vault/vault.go
This commit modifies the Hashicorp Vault backend such that
it returns a more descriptive error when trying to create
a key on the unsupported v2 backend.
The K/V v1 and v2 backends have different APIs for accessing
keys. For example, you access a secret using the `<engine>/<path>`
API on v1. The v2 backend uses the `<engine>/data/<path>` API.
However, the Vault SDK does not return an error when trying to
access a v2 backend with a v1 client. Instead, it returns a secret
object that contains no data but an API warning.
Therefore, we check whether the returned secret contains any data,
and if not, don't return `kes.ErrKeyExists` but send a more descriptive
error event.
=> vault: return more descriptive error for K/V v2 backend

cmd/kes/server.go
This commit adds support for TLS 1.2 in
addition to TLS 1.3.
Some legacy language versions (like Java 8)
do not support TLS 1.3, and therefore, fail
to connect to KES.
However, we want to support only PFS TLS connections.
Therefore, we limit the supported cipher suites to
ECDHE key exchange and AEAD ciphers.
Further, we have to drop ChaCha20-Poly1305 in case
of FIPS 140.
=> add support for TLS 1.2

internal/vault/vault.go
This commit fixes a subtle issue caused by questionable
behavior of the Vault SDK.
When writing an entry to Vault's K/V engine, the Vault
SDK returns an object representing the entry or an error
explaining why the write failed.
However, the Vault SDK may return no entry object and no
error even if writing to Vault failed - e.g. in case of
a broken network connection.
This can cause KES to think that it created a key successfully
while Vault actually didn't receive the request. So, KES may
return 200 OK to its client while the key creation actually failed.
This commit fixes this by checking that we actually got an
entry object from Vault.
=> vault: ensure that a write to Vault actually succeeded

cmd/kes/identity.go, cmd/kes/key.go, cmd/kes/log.go, cmd/kes/main.go, cmd/kes/policy.go
This commit improves the CLI metrics UI.
Now, the UI shows various stats about the
received requests, the KES server endpoint(s)
and audit/error event counters.
=> metrics: improve CLI metrics UI

internal/auth/policy.go, internal/auth/proxy.go
This commit fixes a problem when clients send a certificate chain
during the TLS handshake. KES expects exactly one client certificate
to map it to a policy.
However, we can filter all CA certificates and only consider leaf
certificates as client certificates. This allows clients to send
a certificate chain as long as this chain contains their client
certificate and no other leaf certificate.
Updates #149
=> auth: filter CA certificates when mapping client certificate to policy

internal/metric/metric.go
This commit fixes an issue similar to d51a099.
The type check:
```
var x {
...
flusher: w.(http.Flusher),
}
```
panics if `w` does not implement the `http.Flusher`
interface.
The correct way to check whether `w` implements
`http.Flusher` is:
```
var x {
...
}
if flusher, ok := w.(http.Flusher); ok {
x.flusher = flusher
}
```
=> metric: fix invalid type check for http.Flusher

.github/workflows/go.yml
This commit updates the github actions
- `checkout` to `v2`
- `go-setup` to `v3`
=> ci: update github actions {checkout,go-setup}

enclave.go, integration_test.go, internal/http/enclave-api.go, internal/http/identity-api.go, internal/http/policy-api.go, kestest/server_test.go
This commit adds a KES server API test
that checks which APIs are exported by
the KES server.
Further, this commit fixes several API
errors introduced since `v0.18.0`.
=> kestest: add server API tests

internal/vault/vault.go
This commit fixes a bug in the Hashicorp Vault backend.
Vault returns `200 OK` and `204 No Content` depending
on the K/V version when creating a key.
Before, KES only accepted `204`. Now, KES accepts both
`200` and `204`.
Fixes #224
=> hashicorp: accept `200 OK` and `204 No Content`

cmd/kes/server.go
This commit fixes a UI bug when displaying the reachable
IP endpoints.
Before, the KES server always printed the IPv4 addresses of
all available network interfaces. This is incorrect and can
lead to confusion.
The KES server listens on the specified network interface(s).
This can be a specific network interface:
- e.g. `192.168.188.162`
- the pseudo address `0.0.0.0`
When listening on a specific IP / interface - e.g. `192.168.188.162`
then KES accepts connections only from that interface.
For example a request to `https://192.168.188.162:7373/version` will served
while a connection attempt to `https://127.0.0.1:7373/version` will be
refused.
In particular, listening on `:<port>` resp. `0.0.0.0:<port>` is not
the same as listening on `127.0.0.1:<port>` since the later listens
**only** on …
=> cmd: display server endpoints listening on correctly

cmd/kes/server.go
Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>
=> fix server help typo

internal/http/audit.go, server-config.yaml
This commit adds the enclave name into the
audit log.
=> http: include enclave name in audit log

.github/workflows/codeql.yml, .github/workflows/go.yml, .github/workflows/release.yml, .github/workflows/vulncheck.yml
This commit organizes the CI actions into the
following categories:
- Build
- Test
- Security
=> organize CI actions

cmd/kes/gateway.go, internal/auth/identity.go, internal/auth/policy.go, internal/sys/enclave.go, internal/sys/stateless-vault.go, kestest/policy.go, kestest/server.go
This commit cleans up a bunch of historical
code that is no longer used.
=> all: simplify and remove unused code

kestest/gateway_test.go
This commit adds a test for fetching the
server metrics.
=> kestest: add metrics test

retry.go
This commit causes the client to retry the
request to a different KES server (if any)
when one KES server response with 5xx error
code.
A KES server returning a 5xx error code might
have lost network connection to the KMS.
In such a case, we retry the request until there
are no more KES servers.
=> retry when server returns 5xx error codes

client.go, enclave.go, retry.go
This commit implements stateful client-side
load balancing. A `Client` and `Enclave` now
contain an internal `loadBalancer` which sends
requests to a list of endpoints.
The load balancer marks an endpoint as offline
when an endpoint fails to respond, e.g. due to
a network error or 5xx response code. Offline
endpoints no longer receive requests.
After some time period (currently 5m), the load
balancer marks offline endpoints as online to
check if it has become available. If the endpoint
still fails to respond it gets marked offline again for another 5m.
This process ensures that offline failing endpoints don't receive traffic while at the same time endpoints can become available again.
=> implement stateful client-side load balancing

cmd/kes/gateway.go
This commit prints the KMS type and endpoint
on KES server startup.
=> cmd: print KMS and endpoint on startup

internal/api/status.go
This commit exposes keystore status information
in the `/v1/status` API.
Now, a client application can check whether KES
has access to its keystore (and how big the latency is - rounded to ms). Additionally, the client
can determine whether the keystore is not available or not even reachable by KES.
=> expose keystore status in the `/v1/status` API

cmd/kes/identity.go
This commit fixes some inconsistencies in the
`kes identity new` command.
It mainly updates the command usage to reflect the changes introduced by the API key support.
Fixes #346
=> improve `kes identity new` command

.github/workflows/go.yml, .github/workflows/release.yml, cmd/kes/update.go, go.mod, go.sum, internal/sys/build.go
This has been broken since introduction of date based release tags.
fixes #372
=> fix: kes update command, update it to use proper version tags

.github/workflows/edge-test.yml
This would trigger while PR merge to master and at the moment would execute edge tests for AWS and Azure.
=> Added github actions for edge test for cloud KMS systems

.github/workflows/edge-test.yml
=> ci: use correct runner label for edge tests

.goreleaser.yml
- regression in https://github.com/minio/kes/commit/246de8af1ad93e9d218376c2253cd5008e4548b5
=> Add linux amd64 image for quay

go.mod, go.sum
This commit updates the SDK dependency which includes fix parsing the server status response correctly.
=> update SDK dependency

go.sum
=> Fix go.sum for release

internal/keystore/entrust/keycontrol.go
This commit fixes the HTTP transport of the entrust keycontrol client to use a connection pool to reuse connections or close idle ones.
=> entrust: use reasonable defaults for HTTP transport

cmd/kes/update.go, internal/http/close.go, internal/http/retry.go, internal/keystore/aws/secrets-manager.go, internal/keystore/azure/key-vault.go, internal/keystore/entrust/keycontrol.go, internal/keystore/fortanix/keystore.go, internal/keystore/gcp/secret-manager.go, internal/keystore/gemalto/client.go, internal/keystore/gemalto/key-secure.go
Also ensure that we drain the body before closing to it to reuse the
existing connections when possible.
=> entrust: Close body to avoid some conn leaks

go.mod, go.sum
Update golang.org/x/net library
=> Bump golang.org/x/net to silence a wrong vuln checker

.github/workflows/go.yml, internal/keystore/vault/vault.go
Fixes: https://github.com/minio/kes/issues/515
=> Correct condition check

README.md
- Added a clear definition of KES (Key Encryption Service) at the beginning of the "What is KES?" section.
- Improved user understanding by explicitly stating what KES stands for without disrupting the document flow.
=> docs: Clarify KES (Key Encryption Service) definition in README

cmd/kes/server.go, config.go, internal/crypto/key.go, kesconf/file.go, keystore.go, server.go
Implemented logic to define keys present in config file.
=> Fix for #519
