cmd/kes/config.go, cmd/kes/server.go, server-config.toml, server-config.yaml, vault/vault.go
This commit adds support for Vault namespaces.
A Vault namespace allows separating / isolating
multiple tenants or organisations.
See: https://www.vaultproject.io/docs/enterprise/namespaces/index.html
for more information.
=> vault: add support for namespaces

cmd/kes/server.go
This commit fixes a bug in the identity<->policy
assignment during the server startup.
Now, the server does not assign a policy to the
unknown identity (empty string). Instead, such
policy<->identity mappings are ignored.
The previous behavior was not correct but also
not a security issue since the unknown identity
is always rejected by the server when doing a policy
lookup.
=> fix incorrect identity assignment during startup

client.go, cmd/kes/server.go, handler.go, handler_test.go
This commit improves the validation of
the request URL path. Now, the `ValidatePath`
handler function accepts a API path pattern
and tries to match the request URL path against
this pattern.
Only if the URL path matches that pattern the
request gets handled. Otherwise, we return 400
(bad request) to the client.
This simplifies adding new (more complex) APIs and
makes it easier to think about security implications
(See: directory traversal a.o.).
=> improve API path validation

audit.go, cmd/kes/config.go, cmd/kes/server.go, handler.go, server-config.toml, server-config.yaml
This commit adds basic support for logging
audit events to files.
Therefore, it adds a new `SystemLog` type
that allows attaching and detaching log targets
(files, sockets, http connections, etc.) to
a `log.Logger`.
Now, we can dynamically add and remove log targets
to the currently configured logger. This is in service
for dynamically inspecting and at/detaching to logging -
which will be added in the future. This commit paves
the path for this.
The audit log itself is just a `http.HandlerFunc`
that extracts some "interesting" request parameters
(API path, X.509 identity, ...) and logs them together
with the response before writing back to the client.
At the moment the log contains the current time,
request API path, client identity and response status
code. However, this can be extended …
=> add basic support for audit logging

client.go, cmd/kes/create.go, cmd/kes/server.go, handler.go, handler_test.go
This commit splits the `/v1/key/create` API into
two separate APIs:
- `/v1/key/create`
- `/v1/key/import`
The reason for this API separation is that some
applications may be allowed to create keys - e.g.
a new secret key on their first startup. However,
this applications should probably not be allowed
to specify the secret key itself.
An application that can specify the secret key itself
may be a security issue since it does not necessarily
need the KES server to perform cryptographic operations
with this key.
Therefore, applications should only have the `v1/key/create`
permission (if required) but not the `/v1/key/import` permission.
However, the `/v1/key/import` API may be useful when migrating
from one backend store to another (e.g. from Vault to AWS and vice
versa).
**This is an …
=> split /v1/key/create API into create and import

audit.go, client.go, cmd/kes/audit.go, cmd/kes/main.go, cmd/kes/server.go, go.mod, go.sum, handler.go
This commit adds support for tracing
audit log events.
Therefore, this commit removes the global
HTTP write timeout. The problem with server-wide
timeouts is that as a HTTP handler you cannot
adjust/opt-out of the timeout. This makes it
impossible to implement long-running server tasks
like tracing logs.
Instead, this commit implements a custom timeout
handler - similar to https://golang.org/pkg/net/http#TimeoutHandler
The custom timeout handler and Go's TimeoutHandler
differ in implementation details. See documentation.
Now, each HTTP handler that requires a (write) timeout
must be wrapped by a timeout handler. The server-wide
write-timeout is explicitly set to 0.
Further, this commit implements a audit log tracing CLI
that prints a human-readable text output to a TTY and JSON
otherwise.
=> implement audit log tracing

server-config.toml, server-config.yaml
This commit adjusts the cache expiry
default values to:
- discard all entries after `5 min`
- discard entries that haven't been
used for more then `20 sec`
The value for `all` is reduced significantly
since:
```
1 Month / 5 min = 30 * 24 * 60 / 5 = 8640
```
So, by discarding all cache entries we make 8640
requests to the key store. For ref: AWS charges
per 10,000 requests (e.g. 10,000 req = 0.03 ct).
This means that the KES server has to authenticate
itself to the key store and request access to the
master/secret key every 5 min - which is quite
conservative.
Further, if an application is not using the
master/secret key for more 20 sec the KES
server will discard it as well. This is again
a conservative choice. However, for high-performance
applications 10 sec or less may also be …
=> update cache expiry default values

aws/secrets-manager.go, cmd/kes/server.go
This commit renames the `awsecret` package
to make the API more idiomatic.
Before, `awsecret` should only contain types
and functions related to the AWS SecretsManager.
Therefore, it contained the generic `KeyStore` type.
Now, the package `aws` groups all AWS services that
can be used as key store. So, there is a `aws.SecretsManager`
type that implements a key store using the AWS SecretsManager
as storage.
=> rename package `awsecret` to `aws`

client.go, cmd/kes/main.go, cmd/kes/release.sh, cmd/kes/server.go, handler.go
This commit adds version information to the
binary and the server.
Now, when making a release the commit tag
becomes the release version. So, running
```
cd ./cmd/kes && ./release.sh
```
after tagging a new release (e.g. v1.0.0)
will include `v1.0.0` as version into the binary.
If HEAD has no tag the release script will print
a warning and use `0.0.0-<commit-ID>` as release
version.
The binary version is printed when running:
```
kes --version
```
Further, the server handles GET requests
to `/version` and respond with a JSON object
containing the version of the server.
Note that the `/version` route is available to
anyone who can authenticate (via mTLS) to the
server. There is no policy that allows/denies
access to `/version`.
=> add version information to binary and server

client.go
This commit fixes a bug in the kes client
implementation. Before, the `Version` method
of `kes.Client` used the default HTTP client
instead of the HTTP client of the kes client.
=> fix usage of default HTTP client

cmd/kes/config.go, cmd/kes/server.go, internal/auth/proxy.go, internal/auth/proxy_test.go, internal/http/proxy.go, server-config.toml, server-config.yaml
This commit adds support for TLS proxies such that
there can be 0, 1 or multiple TLS proxies between
one (or more) kes clients and a kes server.
The identity of each proxies (direct neighbor of the kes server)
must be added to `proxy.identities`.
Further, the proxy which is a direct neighbor of the kes client
must forward the kes client certificate as part of the request
header.
So, in the most simple (and most common) case there is one TLS
proxy - e.g. a nginx load balancer - between the kes server and
kes client. This nginx has to extract and forward the client
certificate (request headers) and has to authenticate itself
via its own nginx client certificate to kes as proxy.
Optionally, the nginx may verify the kes client certificate as well.
If there would be two load balancers then the …
=> add support for TLS proxies

client.go, error.go, internal/aws/secrets-manager.go, internal/http/error.go, internal/http/handler.go, internal/http/proxy.go
This commit stabilizes and unifies the error interface
of the KES server. From now on the KES server returns
a error code >= 400 (bad request) and a JSON error message
as response body.
The error response has the following (simple) form:
```
{
"message": "...",
}
```
Now, a client can rely upon the server returning an error status
code and a JSON object explaining why the error occurred.
Further, the client can now easily check whether the server
returned an expected error - e.g. `key not found`
However, this change does not finalize the errors returned by the server
themself but just the general structure of error messages.
=> stabilize server error API

cmd/kes/audit.go
This commit improves the request-response time
printing while tracing the audit log.
Before, the response time has been truncated to
microseconds. However, when a request-response
takes about 1 seconds the printed time may
be 1.123567s.
This commit fixes this by truncating the printed
time to 10s of milliseconds resp. 10 of microseconds.
This ensures that the audit log shows request-response
times like 1.15s or 256.99ms.
When dealing with times smaller than 1 millisecond we
keep the old behavior to show times like 17μs or 117μs.
I haven't observed sub-microsecond response times, yet -
not even on localhost (local network interface roundtrip).
=> pretty-print audit log response time

README.md
This commit adds how to install KES instructions
to the README.md. This is in particularly necessary
since we now support signed releases and the public key
for verification must be presented to users in way that
ensures that it is not modified by an attacker.
With this change the public key is show as part of the README.md
which is part of the git repository. So only people with push/commit
access can change it and if they do the change will be preserved
in the git history (or they have to rewrite the history which most
probably will be detected).
Further, this commit adds docker install instructions.
=> add install instructions to README.md

internal/secret/secret.go, internal/secret/secret_test.go
This commit fixes a cryptographic security issue
w.r.t. wrapping data encryption keys.
The key derivation function (KDF) used when a
data encryption key is sealed is not a PRF.
One way to show that a function is not a PRF is
to proof that there is a relation between different
output values of the function.
In particular, the AES key derivation function used
before has the following property:
```
Let v0, v1, v2 and v3 be 128 bit values (HEX) as following:
v0 = 00000000000000000000000000000000
v1 = 01000000000000000000000000000000
v2 = 00000000000000000000000000000001
v3 = 01000000000000000000000000000001
Further let K be an arbitrary 256 bit key and f the AES key
derivation function. Then invoking f with K and the iv values
returns 4 output values
k0 = f(K, v0)
k1 = f(K, v1)
k2 = f(K, v2) …
```
=> do not use broken key derivation for AES-GCM

cmd/kes/config.go, cmd/kes/server.go, error.go, internal/aws/kms.go, internal/aws/secrets-manager.go, internal/fs/fs.go, internal/http/handler.go, internal/mem/mem.go, internal/secret/cache.go, internal/secret/cache_test.go, internal/secret/ciphertext_test.go, internal/secret/kms.go, internal/secret/secret.go, internal/secret/secret_test.go, internal/secret/store.go, internal/vault/vault.go, server-config.toml, server-config.yaml
This commit implements encrypted secrets.
Before, KES stored all secrets as plaintext at the
backend secret store. Therefore, KES assumed/required
that the secret store is a secure/trusted component.
While this assumption may be true for secret stores like
Vault or AWS SecretsManager it is not true in the general
case. Further, even if the secret store is considered trusted
it may be desirable to separate the trust between the secret
storage provider and another party.
Therefore, a KES server may want to encrypt secrets before
storing them at the secret store. In general, KES encrypts
secrets with an (external) KMS - like Vault, AWS-KMS or
Azure Vault. Therefore, KES sends a secret to the KMS before
writing it to the secret store. However, it doesn't send the
secret as plaintext to the …
=> add initial KMS support for sealed secrets

.github/workflows/go.yml
This commit adds build and test jobs for Go 1.14 to
the CI pipeline.
=> add Go 1.14 to CI

.github/workflows/go.yml, cmd/kes/config.go, cmd/kes/server.go, internal/aws/kms.go, internal/vault/client.go, internal/vault/kms.go, internal/vault/vault.go, server-config.toml, server-config.yaml
This commit adds Vault as KMS provider
to encrypt secrets at the secret store
backend.
Therefore, this commit adds a section
for configuring Vault as KMS provider.
Overall, this commit adds Vault as a
second KMS provider similar to AWS-KMS.
=> add support for Vault as KMS provider

cmd/kes/log.go, cmd/kes/main.go, cmd/kes/server.go
This adds a new CLI sub-command `log` that
provides mechanisms to work with KES server
logs - e.g. trace the server log event stream.
In general, there are two types of log events
produced by a KES server:
- audit events
- error events
The new `log` command will be the starting point
for dealing with both event types. At the moment
the CLI only deals audit event streams. Therefore,
the new `log` command preserves the exact behavior
of `audit`.
So, there is a sub-command `trace` and
`kes log trace` behaves exactly as `kes audit trace`
did before.
In the future, we want to add more and more log
management features to `kes log` - e.g. support
for error log events.
=> add new `log` cmd and deprecate `audit` cmd

cmd/kes/server.go
This commit fixes a bug when initializing AWS-KMS.
Before, the error log was not passed to the AWS-KMS
client such that if the client would log a error message
it would always be written to the STDOUT/STDERR - regardless
what was specified in the config file.
However, this bug does not affect any (official) release
because it has been introduced by 817a824.
=> aws-kms: honor error log configuration

cmd/release/main.go
This commit adds a release command that fetches release
information (i.e. versions) about the `github.com/minio/kes`
module from a Go proxy.
With this command it is possible to add release information
to the KES binary during compilation - without any extra
dependencies (e.g. curl and jq).
The general idea is to first install the release command
via `go install github.com/minio/kes/cmd/release` and then
run:
```
go install -ldflags "-s -w -X main.version=$(release)" github.com/minio/kes/cmd/kes
```
This commit does not update the Dockerfile since we have to
release this change first such that
`go install github.com/minio/kes/cmd/release` succeeds.
=> add release cmd to build versioned binaries with docker

Dockerfile
This commit uses the `release` command added by
08be13b to build a binary with release information
when building the docker image.
This can be verified by running:
```
docker build - < Dockerfile
```
and then
```
docker run <container-id> -v
```
=> build a versioned KES binary in docker container

client.go, cmd/kes/create.go, cmd/kes/decrypt.go, cmd/kes/delete.go, cmd/kes/generate.go, cmd/kes/identity.go, cmd/kes/log.go, cmd/kes/main.go, cmd/kes/policy.go
This commit stabilizes the KES client API.
The `Client` type now exports the KES server
endpoint and the HTTP client.
This is a very flexible API in the sense that
a user can configure any custom transport
configuration (timeouts etc.) or implementation
(TCP-TLS, QUIC, ...).
So, this way the `Client` type can be used even
if the underlying protocol layers will change.
Further, there are two convenience functions:
- `NewClient`
- `NewClientWithConfig`
which will be sufficient for most scenarios
where the user just provides a client certificate
or a TLS configuration.
=> stabilize `kes.Client` and `New*` functions

client.go, retry.go, retry_test.go
This commit implements a request retry mechanism.
Now, client automatically retries a request if
the failure seems to be temporary.
In particular, if e.g. a KES server dies for some
reason before it has sent a response then the client
fails with an `*url.Error` wrapping an `io.EOF` or
an `io.ErrUnexpected`. In this case we retry the request
hoping that the KES server gets (automatically) restarted.
=> implement request retry mechanism for KES client

cmd/kes/main.go
This commit renames the client env. variables used to specify
the client certificate and private key.
Before, the CLI client expected:
```
export KES_CLIENT_TLS_CERT_FILE=<cert>
export KES_CLIENT_TLS_KEY_FILE=<key>
```
Now, the CLI client expects:
```
export KES_CLIENT_CERT=<cert>
export KES_CLIENT_KEY=<key>
```
The reason for this change is that the previous env. variables
are quite verbose and look odd compared to the `KES_SERVER`
variable.
The new variables are more compact and don't require boilerplate
typing.
It has been considered to have a fallback - like if `KES_CLIENT_CERT`
is not present look for `KES_CLIENT_TLS_CERT_FILE`. However, it
seems worse to have a deprecated fallback that gets removed at some
point in time. A clean cut seems better here.
=> rename the KES client env. variables for the client key and cert

cmd/kes/config.go, cmd/kes/server.go, internal/vault/client.go, internal/vault/vault.go, server-config.yaml
This commit allows users to specify a custom
engine path for the K/V secret engine and
AppRole authentication method, and therefore,
fixes #55.
Vault allows engines to be mounted at arbitrary
paths. For instance, you can mount the K/V secret
engine at `/kv` or `/secrets`.
Further, Vault allows multiple instances of the same
engine to be present at the same time. Therefore,
supporting user-defined engine paths is necessary.
The same is true for authentication methods/engines,
like AppRole.
This adds two configuration options `engine: <engine-name>`.
One is for the K/V engine and the other one is for the
AppRole engine.
However, if not specified the server assumes that the
K/V engine is mounted at the "default" `/kv` path and
similarly, that the AppRole engine is mounted at the
"default" …
=> vault: allow custom engine paths

cmd/kes/server.go
This commit fixes a bug in the server initialization
w.r.t. requiring TLS certificate verification of TLS proxies.
Currently, the certificate of the TLS proxy is not validated
by default / when `--auth` is not set to `off`.
However, this has no direct security impact since a TLS proxy
has to be explicitly configured and its public key has to be pinned.
This commit fixes this by always enabling TLS certificate validation
for TLS proxies unless `--auth=off` has been specified.
=> proxy: fix invalid check to enable authentication

client.go, cmd/kes/policy.go, error.go, internal/auth/policy.go, internal/http/handler.go
This commit changes the implementation of the
`/v1/policy/delete` API.
Deleting a policy used to just remove the policy with the
specified name from the policy set. When there were identities
assigned to this particular policy then identities would become
"stale"/"dangling".
If the KES server would encounter a request from an identity that
would be "assigned" to a deleted policy it would deny any access,
as it would if the identity would not be assigned to a policy.
This commit changes the behavior of `/v1/policy/delete` such that
deleting a policy also removes all assigned identities from the
KES server. This behavior is save because:
- An identity can be assigned to (at most) one policy at one point
in time.
- An assigned identity is just a mapping from (external) identity
to a policy. …
=> delete assigned identities when deleting policy

cmd/kes/config.go, cmd/kes/server.go, internal/gemalto/client.go, internal/gemalto/key-secure.go, internal/http/retry.go, server-config.yaml
This commit adds support for Gemalto KeySecure
as KMS.
KeySecure is a KMS implementation developed by Gemalto
(now Thales) and provides a KMIP as well as a REST API.
This commit adds a REST client that uses the KeySecure
secrets API (`/v1/vault/secrets`) to fetch and store
cryptographic keys.
***
KeySecure has multi-user support (username / password).
However, KeySecure also has the concept of refresh and
authentication tokens for programmatic access.
A refresh token is an opaque string, e.g.
`CEvk5cdHLG7si05LReIeDbXE3PKD082YdUFAnxX75md3jzV0BnyHyAmPPJiA0Kgn`,
that can be generated by a user to give an application programmatic
access. With the refresh token an application can request a short-lived
(5 min by default) authentication token. The authentication token
can then be used to perform …
=> gemalto: add support for Gemalto KeySecure

cmd/kes/server.go
This commit adds a `-q, --quiet` flag to the
`kes server` command.
If not specified the server now prints a startup
message that contains the server endpoint(s),
root identity, key store location a.s.o.
If the `-q` flag is specified the server does
not print a startup message and behaves as before.
=> server: add server startup message

.github/workflows/go.yml, integration_test.go
This commit adds a set of integration tests that can be run against a
KES server instance.
To do so:
1. ```
openssl ecparam -genkey -name prime256v1 | openssl ec -out server.key
```
2. ```
openssl req -new -x509 -days 30 -key server.key -out server.cert \
-subj "/C=/ST=/L=/O=/CN=localhost" -addext "subjectAltName = IP:127.0.0.1"
```
3. ```
kes server --key=server.key --cert=server.cert --auth=off \
--root=$(kes tool identity of root.cert)
```
4. ```
go test -v -integration -endpoint=https://127.0.0.1:7373 -k
```
Alternatively, you can also run the integration tests against
`https://play.min.io:7373` via: `go test -v -integration`
=> add integration tests

.goreleaser.yml, Dockerfile.release
This commit fixes the docker CI build by adding
another `Dockerfile.release`.
Now, there are again two docker files and the CI
builds two different docker images:
- One from `Dockerfile` with the tag `:edge`
- One from `Dockerfile.release` with the tag `:latest`
The docker image tagged `:latest` is the latest stable
release while the image tagged `:edge` is the image
built from the latest commit in master.
=> fix the docker CI build by adding Dockerfile.release

.github/workflows/go.yml, README.md, go.mod
Go 1.15 has been released on 2020-08-11. This commit
updates the Go versions in the README.md, module file
and CI configuration to Go version:
- `Go 1.14`
- `Go 1.15`
Go 1.13 has now reached EOL.
=> update Go versions in CI and README

client.go
This commit fixes a bug in the SDK introduced by
945afb7. The SDK incorrectly concatenated the
KES server endpoint and the policy name which
usually causes the client request to fail due to
an pattern mismatch.
To reproduce this bug:
```sh
export KES_SERVER=https://play.min.io:7373
export KES_CLIENT_KEY=<root.key>
export KES_CLIENT_CERT=<root.cert>
kes policy list
```
=> sdk: fix incorrect policy name concatenation

Dockerfile
This commit fixes the docker file for the `minio/kes:edge`
image. The previous docker file incorrectly assumed that
the CI will build and push a docker image as for the `edge`
label to the docker hub.
Now, the docker file clones the minio/kes repo from scratch and
builds the `kes` binary via the Go 1.14 toolchain.
=> fix docker file for edge image

cmd/kes/config.go
This commit changes the behavior of config file parsing.
Now, a KES server rejects config files with unknown fields
by making the decoding strict.
The main reason for this change is that when a user specifies
a non-existing `keys` backend or an existing `keys` backend has
a typo the KES server will start with a in-memory backend key store
instead of reporting an error.
=> reject unknown fields in the yaml config file

client.go, cmd/kes/key.go, cmd/kes/log.go, cmd/kes/server.go, error.go, integration_test.go, internal/aws/secrets-manager.go, internal/fs/fs.go, internal/gcp/secret-manager.go, internal/gemalto/key-secure.go, internal/http/error.go, internal/http/handler.go, internal/http/timeout.go, internal/mem/mem.go, internal/secret/store.go, internal/vault/vault.go
This commit adds a new server API:
```
/v1/key/list/<pattern>
```
This API returns a nd-json stream of
`KeyDescription` objects - each one
describing one key at the KES server.
The key listing API is designed to have
a low memory footprint (since there may
be thousands of keys) even when many
clients try to list keys in parallel.
Therefore, the listing implementation
(at the KES server as well as at the client)
uses iterators to list keys lazy. As soon
as a client disconnects / times out /...
the listing is aborted to not waste server
resources.
This commit also adds a CLI command:
```
kes key list [options] [<pattern>]
```
=> add new server API for listing keys

cmd/kes/server.go, cmd/kes/tool.go, internal/fs/fs.go
This commit replaces the error checks using the `os.Is{...}`
functions - e.g. `os.IsExist(err)` - with the more generic
`errors.Is(err, ...)`.
In general, the `os.Is{...}` functions should not be used.
See: https://github.com/golang/go/issues/41122
=> replace `os.Is{...}` error checks with `errors.Is(err, ...)`

internal/aws/secrets-manager.go
This commit fixes a bug in the AWS SecretsManager
key listing implementation. The previous code stopped
the listing prematurely.
This commit fixes this by returning the correct boolean
value.
=> aws: fix incorrect listing behavior

.github/workflows/go.yml, .golangci.yml, integration_test.go
This commit updates the golang-ci version and
adds some useful linters - like detecting potential
pre-allocation optimizations.
=> ci: update golang-ci version (1.20 -> 1.33)

cmd/kes/config.go, cmd/kes/main.go, cmd/kes/server.go, cmd/kes/tool.go, internal/fs/fs.go
This commit adds a new CLI command:
```
kes tool migrate
Usage:
kes tool migrate [options] [<pattern>]
Options:
--from <PATH>          Path to the configuration file of the server that
should be migrated
--to   <PATH>          Path to the configuration file of the server that
is the migration target
-f, --force            Migrate keys even if a key with the same name exists
at the target. The existing keys will be deleted
--merge                Merge the source into the target by only migrating
those keys that do not exist at the target
-q, --quiet            Don't print migration progress and statistics.
-h, --help             Show list of command-line options
Examples:
$ kes tool migrate --from kes-vault.yml --to kes-aws.yml
```
With the `kes tool migrate` command it is possible to move …
=> cli: add `kes tool migrate` command

integration_test.go, internal/fs/fs.go
This commit fixes a bug in the FS key store.
When a delete occurs the FS key store used to
always return `errDeleteKey` even if the operation
succeeded.
This commit fixes this incorrect behavior.
=> fs: do not return an error if delete succeeds

cmd/kes/config.go, internal/vault/client.go, internal/vault/vault.go, server-config.yaml
This commit adds support for the Vault kubernetes authentication
method: https://www.vaultproject.io/docs/auth/kubernetes
Now, the KES configuration can contain the following K8S auth section:
```
kubernetes:
engine: ""
role:   ""
jwt:    ""
retry:  15s
```
The `engine` allows the customization of the auth path configured
at Vault. It defaults to the Vault default: `kubernetes`.
The `retry` is the delay KES waits before trying to re-authenticate
after connection loss.
The `role` and `jwt` are the credentials received from K8S.
Currently, KES does not support both auth methods (`approle` | `kubernetes`)
at the same time. So, a operator must not set AppRole and Kubernetes
credentials.
=> vault: add support for kubernetes authentication method

integration_test.go, internal/http/handler.go
This commit enables the integration tests for the
key listing API.
Further, this commit fixes a minor bug in the key
listing handler. Now, the KES server always sends
the HTTP header / trailer - even if no keys exists
resp. no keys match the pattern.
=> CI: enable integration tests covering key listing

cmd/kes/config.go, cmd/kes/server.go
This commit adds support for overwriting durations
in the config file (e.g. `cache.expiry.Any`) with
values provided via environment variables.
Therefore, this commit adds a custom duration type
that implements YAML (un)marshaling. The custom
unmarshaling treats durations in the config file
as strings and then checks whether they refer to a
env. variable before it parses it as `time.Duration`
=> config: add env. variable support for durations

cmd/kes/config.go
This commit fixes a bug when merging the
KES configuration with env. variables.
Before, the Vault TLS client certificate
and CA path got replaced by the TLS private
key and TLS client certificate.
Now, the Vault TLS client certificate
and CA path get replaced by the value of
the correct env. variable.
=> fix incorrect lookup of Vault TLS config

client.go, cmd/kes/server.go, go.mod, integration_test.go, metric.go
This commit adds support for KES server
metrics to the client SDK.
Now, a client can fetch the KES server
metrics via the `client.Metrics()` method.
Further, this commit prevents the KES server
metrics from being updated when the metrics
are scrapped. This avoids misleading statistics
that include the metrics gathering as regular
traffic.
=> add metrics support to client SDK

cmd/kes/update.go
avoid repeatedly updating `kes` if already on
the latest version
```
kes -u
```
=> do not update once updated to latest release

cmd/kes/server.go
This commit changes the default behavior of the
server address binding. Before, if no TCP address
(IP:PORT) was specified, the server used `127.0.0.1:7373`.
So, the server would try to listen on port `7373` on
the link-local network interface.
While this behavior is not "wrong" it can lead to confusion
when there are multiple network interfaces and another service
is already listening on the port `7373` - e.g. in case of
docker in combination with port-forwarding:
(host:7373 -> container:7373).
In such a case, the KES server would not be able to listen on
port `7373` on the link-local interface - since it'S already used.
Therefore, an application trying to access the server would experience
errors as if the server is not available:
```
Get "https://localhost:7373/version: read tcp …
```
=> server: listen on all net interfaces by default

.github/workflows/go.yml, .github/workflows/release.yml, .goreleaser.yml
This commit adds Go 1.16 to and removes Go 1.14 from
the CI pipeline.
=> update CI and release pipeline to use Go 1.16

cmd/kes/main.go, cmd/kes/tool.go
This commit adds three new flags to the `kes tool identity new`
command for creating server certificates.
With the `--server` flag the created certificate is valid
for server authentication - instead of client authentication (default).
With the `--dns` and `--ip` flags SANs can be specified.
In general, it is useful to support the creation of server certificates
since e.g. not all openssl versions on major platforms can be used
to create certificates the same way.
For example, the current version of openssl on macOS does not support
the `-san` flag or supports Ed25519.
Now, the documentation can just use the `kes` CLI and does not need
to depend on other tools.
=> identity: add support for creating server certificates

cmd/kes/config.go, cmd/kes/config_v0.13.5.go, cmd/kes/server.go, cmd/kes/tool.go, server-config.yaml
This commit adds a mechanism to create keys in
a declarative way. Now, keys can be specified
in the `keys` section of the config file:
```
keys:
- name: my-key
- name: my-key2
```
The KES server will create these keys before
startup.
This commit is a breaking change. The `keys`
section was used to define the KMS/KeyStore
backend. Now, the KMS backend can be specified
in the `keystore` section.
=> add mechanism to create keys in a declarative way

client.go, client_test.go
The text decoding of data encryption keys produced
incorrect ciphertexts when the encoded text contained
base64-padding bytes.
Now, the decoding sets the length of the decoded ciphertext
to the actual data size.
=> fix decoding of data encryption keys

client.go, internal/metric/metric.go, metric.go
This commit adds two new metrics to the KES server:
- The number of currently active but not yet completed requests
- The server up-time in seconds
Now, the KES server returns the following prometheus text format
when hitting `https://<endpoint>:<port>/v1/metrics`:
```
kes_http_request_active 1
kes_http_request_error 0
kes_http_request_failure 0
kes_http_request_success 2
kes_http_response_time_bucket{le="0.01"} 2
kes_http_response_time_bucket{le="0.05"} 2
kes_http_response_time_bucket{le="0.1"} 2
kes_http_response_time_bucket{le="0.25"} 2
kes_http_response_time_bucket{le="0.5"} 2
kes_http_response_time_bucket{le="1"} 2
kes_http_response_time_bucket{le="1.5"} 2
kes_http_response_time_bucket{le="3"} 2
kes_http_response_time_bucket{le="5"} 2
kes_http_response_time_bucket{le="10"} 2 …
```
=> add active request and uptime metrics

dek-example_test.go
This commit adds one (out of many) possible
examples on how to use a generated key for
a cryptographic operation. In this case, the
key is used to encrypt a short message with
AES-GCM.
Fixes #116
=> add example for generating a new key

client.go
This commit fixes a bug when converting Prometheus
metrics into a struct type. Before, the `+Inf` bucket
was not ignored. This lead to confusing metrics output
containing a negative duration entry.
```
{
"RequestOK": 50979,
"RequestErr": 1814,
"RequestFail": 0,
"RequestActive": 0,
"LatencyHistogram": {
"-1000000": 52793,
"10000000": 52701,
"100000000": 52780,
"1000000000": 52793,
"10000000000": 52793,
"1500000000": 52793,
"250000000": 52780,
"3000000000": 52793,
"50000000": 52775,
"500000000": 52790,
"5000000000": 52793
},
"UpTime": 159265000000000
}
```
This commit fixes this by checking whether the bucket
is the `+Inf` bucket.
=> metrics: exclude the +Inf bucket when parsing metrics

cmd/kes/log.go, internal/xterm/table.go, metric.go
This commit adds the `--type=metric` option
to the `kes log trace` command. When the
`metric` type is specified then the CLI will
fetch the server metrics periodically and either
output a nd-JSON stream of metrics or display
the metrics in a table-like view:
```
┌───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│  0-10ms   │  10-50ms  │ 50-100ms  │ 100-250ms │ 250-500ms │ 500ms-1s  │  1-1.5s   │  1.5-3s   │   3-5s    │   5-10s   │
├───────────┼───────────┼───────────┼───────────┼───────────┼───────────┼───────────┼───────────┼───────────┼───────────┤
│  219489   │    803    │    114    │    89     │    75     │    27     │     6     │    19     │     2     │     3     │ …
```
=> cli: fetch and visualize server metrics

cmd/kes/key.go
Before, an incorrect check caused the CLI to not pass
the correct context value to the server when decrypting
some data.
=> cli: fix incorrect handling of the context argument

cmd/kes/main.go, cmd/kes/tool.go, go.mod, go.sum, internal/fips/api.go, internal/fips/fips.go, internal/fips/nofips.go, internal/secret/secret.go, internal/xterm/table.go
This commit adds a `internal/fips` package.
Now, the KES server / CLI can be built using
the Go BoringCrypto FIPS 140 module. This module
is only available on linux/amd64.
In FIPS mode, a KES server will only used NIST/FIPS
approved primitives and reject any ciphertexts (including
valid ones) generated e.g. using ChaCha20-Poly1305.
=> add internal/fips package for FIPS 140 support

.golangci.yml, client.go, retry.go
This commit adds support for multiple KES server
endpoints to the client.
Now a client contains a list of KES server endpoints:
```
Endpoints: []string {
"https://kes1.domain.local",
"https://kes2.domain.local",
},
```
If a client has multiple endpoints it will pick one
at random for each request. Two subsequent requests
may be sent to two different KES server instances.
The client will try to send one request multiple
times to the same server in case of a tmp. network
error (retry mechanism) before it gives up and tries
to reach the next KES server. It will continue until
it either got a HTTP response or it has tried all
KES server endpoints.
Multiple endpoints should only be specified if
no round-robin DNS is used. Instead, it can be
used as alternative to a server-side load-balancer.
=> client: add support for multiple server endpoints

.golangci.yml, cmd/kes/config.go, internal/gemalto/key-secure.go, internal/generic/client.go, internal/generic/server.go, internal/generic/spec-v1.md, server-config.yaml
This commit adds a generic KeyStore plugin API
to the KES server.
Now, the KES server can talk to an external plugin
that implements four REST endpoints for creating,
listing, accessing and deleting keys.
This commit also adds the plugin specification.
With KeyStore plugins it is possible to support
proprietary/custom KMS/KeyStore implementations
that should not be published.
For a more detailed explanation about plugins
and how they should be implemented take a look
at the generic/spec-v1.md
=> plugin: add generic KES KeyStore plugin v1

client.go, cmd/kes/server.go, internal/metric/metric.go, metric.go
This commit adds two metrics counting the number
of error resp. audit events.
Further, accessing the `/v1/metrics` API does no
longer produce an audit event. The `/v1/metrics`
was already excluded from the metrics collection.
It is also very unlikely that any audit log monitoring
is interested in the `/v1/metrics` API. A monitoring
system (e.g. Prometheus) will scrape the `/v1/metrics`
endpoint quiet often (every few seconds) leading to a
lot of audit event "noise".
Therefore, this PR disables audit events for the `/v1/metrics`
endpoint. If comprehensive audit events are desired this
can be enabled - as an option - in the future.
Now, the KES server metrics contains two additional counters:
```
kes_log_audit_events 2
kes_log_error_events 3
```
=> metric: add counters for error and audit events

client.go
This commit fixes a bug the client SDK introduced by b9e4806.
The `ListPolicies` client SDK call should use an HTTP GET request
instead of a POST request to fetch the policies.
Currently, the client SDK fails to list policies an returns a
`MethodNotAllowed` error.
=> client: fix ListPolicies HTTP method

retry.go
This commit sets the `GetBody` callback when a request body
is present. The callback may be used by the underlying HTTP
stack eventually to obtain a new copy of the request body.
One example are server redirects. In case of a redirect the
client has to send the request again - including the request
body.
In particular, this should also fix the following HTTP/2 error:
```
http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY]
after Request.Body was written; define Request.GetBody to avoid this error (*url.Error)
```
Signed-off-by: Andreas Auernhammer <aead@mail.de>
=> retry: set GetBody callback when request body is present

cmd/kes/config.go, cmd/kes/config_v0.14.0.go, cmd/kes/policy.go, cmd/kes/server.go, integration_test.go, policy.go, policy_test.go, server-config.yaml
This commit adds `deny` rules - in addition to
the existing `allow` rules.
Before, a KES server policy contained a list of
patterns. If a request URL path matches any of
the pattern the request was accepted.
Now, a KES server policy can also contain a list
of `deny` patterns. If a request URL path matches
any of the `deny` patterns then the request is
rejected.
This is an API breaking change since the JSON representation
of a policy is changed by this commit. However, this
is acceptable since we have not committed to a stable `v1.0.0`
version, yet. From now on, more fields can be added to the KES
policy representation backwards-compatibly.
Before, a KES policy had the following format:
```
policy:
my-policy:
paths:
- /v1/key/create/*
- /v1/key/delete/*
identities:
- ...
```
From now on, a …
=> policy: add deny rules

client.go, cmd/kes/identity.go, error.go, identity.go, internal/http/handler.go
This commit modifies the `/v1/identity/list` API
to respond a nd-json stream of identity<->policy
mappings instead of one (eventually large) json
object.
The `/v1/identity/list` API is now similar to
the `/v1/key/list` API.
With the streaming API, a client can iterate over
some/all identities while using just a constant
amount of memory.
This is a major breaking API change.
=> use streaming API for listing identities

error.go, internal/secret/secret.go, internal/secret/secret_test.go
This commit adds a `ErrDecrypt` that is returned by
the KES server when it fails to decrypt an encrypted
ciphertext.
It allows clients to reliably distinguish decryption
errors from other errors - like invalid ciphertext format
or internal server errors.
=> add ErrDecrypt error

internal/http/proxy.go
This commit fixes a bug in the `TLSProxy` handler function
that occurs when KES does not create an audit log entry for
the request. This happens only in case of `/v1/metrics` API.
In case of a `/v1/metrics` API request, KES will not create
an `AuditResponseWriter`. In this case, a type check:
`aw, ok := w.(*AuditResponseWriter)` will result in `aw == nil`.
Therefore, not the assumed `AuditResponseWriter` but the actual
`http.ResponseWriter` must be passed to any subsequent handler.
=> proxy: avoid passing nil as http.ResponseWriter to handlers

cmd/kes/server.go, internal/gemalto/key-secure.go, internal/http/timeout.go, internal/log/log.go
This commit improves the handler timeout
implementation such that:
- No more sporadic data races (concurrent map writes) occur
- Panics in the actual HTTP handler no longer get propagated,
and therefore, shadowed by the timeout handler.
Per handler timeouts are necessary since some handler (i.e.
log tracing) should not time out while others, like key generation,
should time out after a short period of time.
However, the Go HTTP server implementation only supports global
timeouts.
Therefore, this commit has apply some tricks to start an HTTP handler
in a separate Go routine and safely abort it once the timeout exceeds.
One major problem is that the timeout handler has to recover from a
potential panic within the actual HTTP handler and abort the request
without shadowing the panic message …
=> improve request timeout handling

integration_test.go
This commit enables the policy and identity CI tests
again since the KES instance at `https://play.min.io:7373`
has been updated to version `v0.15.0`.
Between `v0.14.0` and `v0.15.0` there have been some breaking
API changes w.r.t. policies that made it necessary to disable
these CI tests.
=> test: enable policy and identity CI tests

internal/secret/cache.go, internal/secret/cache_test.go, internal/secret/secret.go, internal/secret/secret_test.go, internal/secret/store.go
This commit adds unique key IDs to generated
ciphertexts. The key ID identifies the root/master
key used to generate the ciphertext. Now it is possible,
to determine whether a particular key was used to encrypt
a certain ciphertext.
However, the key ID is just for informational purposes.
It is derived from the root/master key content as:
```
id := HEX(SHA-256(key)[:16])
```
The ID is a truncated hash for two reasons:
1. Avoid additional size overhead
2. Limit the damage a broken hash function (i.e. SHA-256)
could cause.
W.r.t. truncating SHA-256 to 128 bits:
This is not a security issue but instead a common technique.
In particular, SHA-224 is truncated SHA-256 and SHA-384 is truncated
SHA-512.
Truncating the hash only reduces the collision resistance boundary.
However, we are not …
=> secret: add key ID to encrypted keys

internal/http/timeout.go
This commit fixes an incorrect type conversion
in the http timeout handler implementation.
Code like `x := y.(Interface)` leads to a panic
at runtime. Instead, you have to check the type
conversion:
```
var x Interface
if t, ok := y.(Interface); ok {
x = t
}
```
=> http: fix type conversion in timeout handler

cmd/kes/config.go, server-config.yaml
This commit changes the default behavior when no cache
expiry has been specified via the configuration file.
Before, KES never removed a key from the cache if no
cache expiry has been specified.
Now, KES sets a default any expiry of 5 minutes and
a default unused expiry of 30 seconds. Those defaults
only apply if the user did not specify a cache expiry,
resp. set the expiry to 0.
=> cache: if no cache expiry is provided, set default expiry

cmd/kes/config.go, internal/fortanix/keystore.go, server-config.yaml
This commit adds a Fortanix SDKMS keystore
backend. Now, Fortanix SDKMS can be used
to store and fetch keys.
This commit only implements a single authentication
method: API keys. It does not support other authentication
methods like JWT, LDAP, Google Service Accounts, ...
A minimal KES<--->Fortanix configuration may be:
```yaml
root: 3ecfcdf38fcbe141ae26a1030f81e96b753365a46760ae6b578698a97c59fd22
tls:
key: private.key
cert: public.crt
keystore:
fortanix:
sdkms:
endpoint: "https://sdkms.fortanix.com"
credentials:
key: "NWMyMWZlNzktZDRmZS00NDFhLWFjMzMtNjZmY2U0Y2ViMThhOnVpUElyWUlhc2FIdkExLVRUOXJFa0ZpSnVPaVpEQTFKZ2hzYUZGT29mcmd3UEJwUnZmcmM0REJzd2UwTk5vSF9oU3BzTGlJN0o2Z3JUTEFPaVR0bV9B"
```
=> fortanix: add support for Fortanix SDKMS

internal/http/timeout.go
This commit uses Go's http.TimeoutHandler
to implement request timeouts and removes
the custom timeout handler implementation.
=> http: simplify request timeout handling

api_test.go, cmd/kes/server.go, identity.go, internal/http/handler.go, internal/http/handler_test.go, internal/http/proxy.go, internal/http/server.go, internal/http/timeout.go, internal/http/tls.go, kestest/example_test.go, kestest/policy.go, kestest/server.go
This commit introduces a new sub-package
`kestest` that contains utilities for
end-to-end KES testing.
It is heavily inspired by the `net/http/httptest`
package and contains a `Server` type that implements
a minimal KES server.
The new `kestest` package makes it possible to
write unit tests covering end-to-end usage scenarios
without a dedicated KES server for testing purposes.
Fixes #164
=> testing: new package kestest

cmd/kes/server.go
This commit fixes the server startup
message that displays the admin identity.
It restores the previous behavior of printing
the identity value. Currently, the server
prints the identity value twice.
This bug has been introduced by a229d68fd.
=> fix printed admin identity on startup

cmd/kes/server.go, internal/aws/secrets-manager.go, internal/azure/key-vault.go, internal/fortanix/keystore.go, internal/fs/fs.go, internal/gcp/secret-manager.go, internal/gemalto/key-secure.go, internal/generic/client.go, internal/http/handler.go, internal/http/server.go, internal/key/store.go, internal/mem/mem.go, internal/vault/vault.go, kestest/server.go
This commit changes the `/v1/status` API by:
- adding a backend KMS status
- removing the TLS certificate information
The KMS status is generic for all KMS backends
and describes whether the backend KMS is reachable
or unreachable as well as the network latency between
KES and the backend KMS instance.
The TLS certificate information got removed from the
status API since this information can be gathered by
the client itself (by looking at the TLS certificate).
Exposing this information in the status API is particularly
useful and just bloats the API.
=> status: expose backend KMS status

cmd/kes/policy.go
This commit fixes a bug in the `kes policy add` command.
Before, the command would create a policy with the name
`add` instead of whatever policy name has been specified.
=> cli: use correct policy name instead of command name

cmd/kes/server.go, internal/fs/fs.go, internal/key/manager.go, internal/key/store.go, internal/yml/server-config.go, internal/yml/server-config_v0.13.5.go, internal/yml/server-config_v0.14.0.go, internal/yml/server-config_v0.17.0.go, server-config.yaml
This commit adds offline caching of keys.
KES keeps keys - fetched from the KMS key
store - in a in-memory cache to increase
performance and reduce the request rate
to the central KMS.
Entries in the cache expiry after a configurable
time period and get removed by a cache GC.
Usually it is recommended to keep the cache
expiry periods quite low - e.g.:
- Any:    5m0s
- Unused:  20s
In particular, low cache expiry values reduce
the time window KES can operate without interacting
with the central KMS when serving stateless
requests; e.g. generating a new data encryption key.
Note that KES can never server stateful requests,
like creating or deleting a key, without the KMS.
Especially in distributed setups, two KES servers
will sync eventually once their cache entires have
expired. For …
=> cache: add offline caching of keys 

internal/vault/config.go, internal/vault/config_test.go
This commit fixes a bug introduced by a229d68
that ignores the K/V prefix when cloning the
Vault config.
This commit fixes this bug and adds a test to
ensure that a config is cloned as expected.
Fixes #178
=> vault: include K/V prefix when cloning config

internal/yml/server-config.go, internal/yml/server-config_v0.13.5.go, internal/yml/server-config_v0.14.0.go, internal/yml/server-config_v0.17.0.go
This commit fixes a regression introduced by
a229d68.
Identities assigned to a policy in the YAML
config file have been ignored in the following
case:
```
policy:
- my-policy:
allow:
- /v1/key/create/*
identity:
- ${MY_CLIENT_IDENTITY}
```
Before, the config file parsing expected
`identities` - not `identity`. After a229d68
`identities` has been ignored. This commit
fixes this by reverting to the previous behavior
of only honoring `identities`.
Fixes #180
=> yml: fix regression parsing policy definitions

cmd/kes/config.go, cmd/kes/server.go, internal/auth/identity.go, internal/auth/policy.go, internal/auth/proxy.go, internal/http/handler.go, internal/http/proxy.go, internal/http/server.go, internal/sys/enclave.go, internal/sys/stateless-vault.go, internal/sys/vault.go, kestest/policy.go, kestest/server.go
This commit adds the most minimal multi-tenancy
implementation.
Now, KES contains an internal Vault. The Vault
has one or multiple Enclaves. (For now just one).
Each Enclave has its own key store, policies set
and identity set. A client selects the enclave
using the `?enclave=<name>` query parameter.
For example:
```
https://127.0.0.1:7373/v1/key/create/my-key?enclave=tenant-1
```
However, a stateless KES server will only support a
single Enclave. Therefore, this commit only adds the
most basic Vault implementation.
Future Vault implementations (e.g. a standalone FS
KES server) will use a more sophisticated Vault
implementation that supports seal/unsealing etc.
This commit mainly focuses on changing the current
code base to use a `sys.Vault` and don't change any
client-facing behavior.
=> sys: add minimal multi-tenancy support via Enclaves

internal/auth/proxy.go, internal/http/audit.go, internal/http/handler.go, log.go
With this commit the KES server adds the
client IP address to the audit events.
```
{
"time": "2022-02-09T23:13:22+01:00",
"request": {
"ip": "127.0.0.1",
"path": "/v1/log/audit/trace",
"identity": "3ecfcdf38fcbe141ae26a1030f81e96b753365a46760ae6b578698a97c59fd22"
},
"response": {
"code": 200,
"time": 45000
}
}
```
=> include client IP address in audit log

cmd/kes/key.go, enclave.go, integration_test.go, internal/http/handler.go, key.go
This commit removes the HTTP trailer mechanism used
to signal errors. Instead, errors are now communicated
as API messages.
Further, this commit extends the listing API with additional
identity information like `CreatedAt` or `CreatedBy`.
Those fields will be used once KES can store keys itself.
=> remove HTTP trailers from `v1/key/list` API

error.go, error_test.go
This commit adjusts the exported errors
to be more descriptive. For example,
`ErrNotAllowed` can not just occur when
a policy disallows the request.
This commit ensures that errors sent by
a previous KES server version are translated
properly. However, it's still a breaking change.
=> adjust exported error messages

cmd/kes/identity.go, enclave.go, error.go, identity.go, internal/http/handler.go
This commit removes the HTTP trailer mechanism used
to signal errors. Instead, errors are now communicated
as API messages.
Further, this commit extends the listing API with additional
identity information like `CreatedAt` or `CreatedBy`.
=> remove HTTP trailers from `v1/identity/list` API

internal/http/handler.go
This commit fixes a bug in the policy API
that probably was introduced as rebase error.
The current `/v1/policy/assign` API uses parts
of the previous `v1/identity/assign` API such
that clients cannot assign a policy to an identity.
=> http: fix `/v1/policy/assign` API

cmd/kes/log.go
This commit fixes a terminal UI issue in the
`kes log` command. Before, the log command
would wrap the API path when it exceeds a certain
length.
Now, each log event is printed on a single line.
=> log: print audit events on a single line

.golangci.yml, internal/auth/proxy.go, internal/cli/alignment.go, internal/cli/fmt.go, internal/gcp/config.go, internal/generic/client.go, internal/http/api.go, internal/http/flush.go, internal/sys/enclave.go, internal/sys/vault.go, internal/vault/config.go, internal/yml/types.go, kestest/server.go
This commit enables all excluded issue-checks.
The excluded error format warning was unnecessary
anyway.
Further, all reported undocumented APIs are now
documented.
=> CI: remove `golang-ci` issue excludes

client.go, cmd/kes/config.go, enclave.go, identity.go, internal/auth/identity.go, internal/http/api.go, internal/http/identity-api.go, internal/sys/enclave.go, kestest/policy.go, kestest/server_test.go
This commit adds a new server API endpoint:
```
/v1/identity/self/describe
```
The server already exposes an API for obtaining
information about an identity:
```
/v1/identity/describe
```
The later one allows a client to query information
about arbitrary identities - as long as the client
has sufficient policy permissions to do so.
In contrast, the new `/v1/identity/self/describe`
API allows any client to request identity and policy
permissions of **itself**.
It does not allow any client to obtain identity / policy
information about any identity other the one making the
request.
With this API, a client can self-inspect its policy permissions.
For example, a client can first check whether it has sufficient
API permissions before sending a request.
=> add `/v1/identity/self/describe` API

client.go, client_test.go, enclave.go, internal/http/api.go, internal/http/key-api.go, kestest/server_test.go, key.go
This commit adds a new bulk API:
```
/v1/key/bulk/decrypt
```
Now, a client can request the corresponding
plaintext / context pairs for multiple
ciphertext / context pairs in a single call.
Before, a client had to send each plaintext / context
pair to the server using the `/v1/key/decrypt` API.
The new bulk API expects an array of ciphertext / context
pairs. Each context is still optional but must match
the context used during encryption:
```json
[
{
"ciphertext": "...",
"context":"..."
},
{
"ciphertext":"..."
},
{
"ciphertext":"...",
"context":"..."
}
]
```
It will respond either with an array of plaintexts
or the first decryption error. It only returns
plaintexts if and only if it decrypted
all ciphertexts successfully.
```json
[
{
"plaintext": "...",
},
{
"plaintext":"..."
},
{ …
```
=> add bulk decryption API `/v1/key/bulk/decrypt`

cmd/kes/identity.go
This commit fixes a indentation issue
in the `kes identity new` command.
```
kes identity
Usage:
kes identity <command>
Commands:
new                      Create a new KES identity
of                       Compute a KES identity
ls                       List KES identities
rm                       Remove a KES identity
Options:
-h, --help               Print command line options
```
Fixes #211
=> cmd: fix identity command indentation

client.go, internal/http/generic-api.go, server.go
This commit adds the client-side functionality to
fetch the server APIs. A client can now use
```
client.APIs(context.Context) ([]API, error)
```
It returns a list of server APIs. A client may
use this to determine whether the KES server
supports a particular API without complex
version negotiation logic.
Further, a graceful clients can fetch API information
like timeouts or max. request body sizes dynamically.
=> add client-side functionality to detect server APIs

internal/fips/fips.go, internal/fips/nofips.go
This commit adds support for the
`+build` directive that was used
in older Go versions.
This change is needed for building
with Go1.16.6 due to a major issue
in Go1.17.x.
=> support `+build` build tag comments

cmd/kes/key.go
This commit aligns the output of the
`kes key {encrypt,decrypt,dek}` commands.
Further, it fixes a bug in the `kes key dek`
command. Before, `dek` wrote hex-encoded
a plaintext/ciphertext pair to STDOUT (when
redirected) -  instead of base64.
Now, the output is again encoded as base64.
=> cmd: align `kes key` command output

client.go, internal/metric/metric.go, metric.go
This commit exposes the number of
usable CPUs - in addition to the
number of available CPU cores.
The number of available CPU cores
shows how many logical CPU cores
are present on the system.
However, the KES server may only
use a subset of these CPUs.
For example when `GOMAXPORCS` is set.
The number of usable CPU cores,
exposed by this commit, shows how
many logical CPU cores can be used
by the KES server.
It may be less then or equal to the
number of available CPUs.
=> metric: expose usable CPUs

go.mod, go.sum
This commit updates the prometheus (`github.com/prometheus/client_golang`)
to `v1.11.1`.
=> dep: update to prometheus `v1.11.1`

.golangci.yml, cmd/kes/server.go, go.mod, go.sum, integration_test.go, internal/aws/secrets-manager.go, internal/azure/key-vault.go, internal/cpu/aes.go, internal/fortanix/keystore.go, internal/fs/fs.go, internal/gcp/secret-manager.go, internal/gemalto/key-secure.go, internal/generic/client.go, internal/http/key-api.go, internal/key/algorithm.go, internal/key/ciphertext.go, internal/key/key.go, internal/key/key_test.go, internal/vault/vault.go
This commit moves from JSON-encoded
DEKs to binary-encoded DEKs.
Previously, generated JSON-encoded
DEKs can still be decrypted. Newly,
generated DEKs are now encoded in
a binary message-pack format.
This decreases the size of DEKs
roughly about 35%.
Further, this commit adds
algorithm-specific keys. In general,
a crypto. key should be specific for
one crypto. algorithm. For example,
`AES256-GCM_SHA256`.
A key that is specific for a particular
algorithm cannot be used in other algorithms.
=> key: switch to binary-encoded DEKs

.github/workflows/go.yml
This commit updates the CI tests to use Go 1.18.
=> update Go version of CI tests

integration_test.go, internal/vault/vault.go
This commit fixes an issue in the Vault
health-check logic.
Before, KES always opened a TCP connection
to Vault. In case of TLS, this causes Vault
to log a TLS handshake error for every KES
status check.
Now, KES only tries to check if Vault is reachable
at all if the regular health-check fails.
So, we have run the health check in reverse order.
Fixes #230
=> vault: issue health check before dialing

cmd/kes/config.go, internal/gcp/config.go, internal/gcp/secret-manager.go, internal/yml/server-config.go, internal/yml/server-config_v0.13.5.go, internal/yml/server-config_v0.14.0.go, internal/yml/server-config_v0.17.0.go, server-config.yaml
This commit adds support for custom OAuth2 scopes.
On GCP / GKE an instance / application can have
custom OAuth2 scopes. The scopes define which APIs
the application / instance can access.
Before, KES always used the default scopes and
didn't provide a way to specify custom scopes.
This can lead to authentication failures to GCP
when custom scopes are used.
Now, custom scopes can be specified via the `scopes` option:
```
scopes:
- "scope-1"
- "scope-2"
- ...
```
=> gcp: add support for custom OAuth2 scopes

.github/workflows/go.yml, .github/workflows/release.yml, .goreleaser.yml, cmd/kes/main.go, cmd/kes/server.go, cmd/kes/update.go, go.mod, internal/fortanix/keystore.go, internal/http/api.go, internal/http/generic-api.go, internal/sys/build.go, kestest/server.go
This commit adds binary build information
exposed by the `runtime/debug` information
introduced by `Go 1.18`.
Since Go 1.18, the Go compiler compiles
build information into the binary.
This information is accessible using
`go version -m <binary-file>`
Now, KES uses this build info to expose
the binary version, commit ID, ...
Therefore, KES looks at the build tags,
specifically the `-tags` flag:
```
go build -trimpath -tags "version={version}" -o ~/go/bin/kes github.com/minio/kes/cmd/kes
```
=> use build information from `runtime/debug`

Dockerfile
The minimum requirement is go 1.18, Build is failing on go 1.17!
=> Bump go1.17 to 1.18 

cmd/kes/server.go, internal/fips/api.go
This commit adds two new functions to the `fips` package:
- `TLSCiphers()`
- `TLSCurveIDs()`
The first one returns a list of supported TLS cipher suite IDs.
The list will differ depending upon running in FIPS-mode or not.
However, Go's TLS stack will still negotiate the "best" cipher
for the particular connection.
The second one returns a list of supported elliptic curve IDs
used by the TLS stack for ECDHE key exchange. The curve IDs are
returned in preference order and the Go TLS stack should choose
the first curve supported by the client.
In case of TLS 1.3, the curve used by the client may be used directly
(if supported) since one-way roundtrip.
The P-384 and P-521 curves are enabled now since the Go standard library
supports constant time implementations for these curves.
=> fips: simplify TLS configuration

client.go, cmd/kes/status.go, internal/http/generic-api.go, server.go
This commit improves the `kes status` command.
It exposes the number of CPUs and heap/stack memory
usage via the status API.
The `kes status` command now prints this CPU and memory
info.
```
● play.min.io:7373
Version  0.19.2
Uptime   2 days 4 hours
Latency  562ms
CPUs     4
Memory
· Heap   2 MiB
· Stack  708 KiB
```
Further, this commit adds two flags to the `kes status` command:
- `--api`
- `--short`
The `--short` shows only summary information:
```
● play.min.io:7373
```
The `--api` flag lists all server APIs additionally to the
status information:
```
● play.min.io:7373
Version  0.19.2
Uptime   2 days 4 hours
Latency  562ms
CPUs     4
Memory
· Heap   2 MiB
· Stack  708 KiB
Method  API                          Timeout
GET     /version                     15s
GET     /v1/status …
```
=> cmd: improve `kes status`

cmd/kes/color-option.go, cmd/kes/identity.go, cmd/kes/key.go, cmd/kes/policy.go, cmd/kes/status.go, identity.go, key.go, policy.go
This commit simplifies the listing code
by introducing the `Values(n int)` method
on the `{Key|Identity|Policy}Iterator`.
Further, this commit adds a color option
flag that controls the colorization of the
output. For example:
```
$ kes key ls --color always | cat
```
=> cmd: improve listing and output colorization

cmd/kes/identity.go, enclave.go, internal/http/identity-api.go
This commit adds the `kes identity info` command.
If no identity argument is passed, `info` fetches
information about the client identity itself via
the `/v1/identity/self/describe` API. The output
mainly differs for admins and regular users.
```
$ kes identity info
Identity    c40bca7bfa2e4e92cd61f56580b9b7f2e5c356b6443ca6960df877ecce2e8016
Created At  2022-06-28 10:39:33
Role        User
Created By  3ecfcdf38fcbe141ae26a1030f81e96b753365a46760ae6b578698a97c59fd22
Policy      minio
Created At  2022-06-28 10:30:21
Allow
· /v1/key/create/*
· /v1/key/generate/*
· /v1/key/decrypt/*
· /v1/key/bulk/decrypt/*
Deny
· /v1/key/decrypt/my-internal*
```
```
$ kes identity info
Identity    3ecfcdf38fcbe141ae26a1030f81e96b753365a46760ae6b578698a97c59fd22
Created At  2022-06-20 12:32:28
Role …
```
=> cmd: add `kes identity info` command

internal/http/retry.go, internal/http/tls.go, internal/vault/client.go
timers can trickle memory alloc quite
sharply over a period of time for days.
Since the memory build up is so slow,
the buildup is not easily visible,
additionally there is a cost to always
invoking runtime timer in a loop.
This PR is an attempt to address this
by reusing the timer by creating it
once and making sure to use the right
amount of "Reset()" to wait for expected
lengths.
Additionally fixes a timer leak in
ReloadAfter() certificate reload function.
=> improve timer usage by re-using them

go.mod, go.sum, internal/metric/metric.go
This commit adds the HTTP response code to the
response status (success, error, failure) metrics.
Now, the response status metrics are partitioned by
the status code.
=> metric: add response code as label to status metrics

error.go, error_test.go, retry.go, retry_test.go
This commit adds the `ConnError` type. A `ConnError`
is returned by a `Client` or `Enclave` to indicate
that an operation failed due to a network issue.
For example, a DNS error.
Users may check whether an operation return an
error of type `ConnError` and act appropriately.
=> error: add `ConnError` type for network connection errors

client.go, cmd/kes/identity.go, cmd/kes/policy.go, enclave.go, kestest/server_test.go
This commit adds the `kes policy info` command.
It prints information about a KES policy.
Further, this commit adds the SDK function
`DescribePolicy` that calls the `/v1/policy/describe`
API which already exists.
```
$ kes policy info minio
Name        minio
Date        2022-06-22 11:40:08
Created by  3ecfcdf38fcbe141ae26a1030f81e96b753365a46760ae6b578698a97c59fd22
```
=> cmd: add `kes policy info` command

cmd/kes/server.go, internal/cli/fmt.go, internal/cli/init.go, internal/sys/fs/init.go
This commit adds support for a TLS reverse proxy for stateful
servers. The TLS proxy has to behave like for a stateless server.
For more information around TLS reverse proxies and KES see:
https://github.com/minio/kes/wiki/TLS-Proxy
=> tls: add support for TLS reverse proxies to stateful server

cmd/kes/init.go, internal/cli/init.go
This commit adds declarative policy assignments
for the stateful KES init config.
Now it is possible to pre-define identities and
there policies in the init config:
```
policy:
minio:
allow:
- /v1/key/create/*
- /v1/key/generate/*
- /v1/key/decrypt/*
- /v1/key/bulk/decrypt/*
deny:
- /v1/key/decrypt/internal-*
- /v1/key/bulk/decrypt/internal-*
identities:
- c40bca7bfa2e4e92cd61f56580b9b7f2e5c356b6443ca6960df877ecce2e8016
```
During `kes init` the specified policy will be assigned to
all listed identities. This is a nice quality-of-life
improvement when deploying KES on e.g. K8S.
The `init` command will make sure that within the same enclave,
an identity can only be assigned to one policy and that the
identity is not equal to the sys admin or the enclave admin.
=> init: define policy assignments in init file

cmd/kes/gateway.go, internal/auth/identity.go, internal/http/api.go, internal/http/gateway-api.go, internal/http/gateway-identity-api.go, internal/http/gateway-key-api.go, internal/http/gateway-log-api.go, internal/http/gateway-policy-api.go, internal/http/gateway.go, internal/http/server-api.go, internal/http/server-enclave-api.go, internal/http/server-identity-api.go, internal/http/server-key-api.go, internal/http/server-log-api.go, internal/http/server-policy-api.go, internal/http/server-sys-api.go, internal/http/server.go
This commit separates the stateful and stateless server (gateway)
implementation.
In particular, the abstracts for the gateway (e.g. KMS key store)
and the stateful server cause additional complexity and often
leak the underlying implementation or are fundamentally incorrect.
For example, the gateway should be stateless and read-only (except
for the managed keys) while the server require modifications to
policies, identities etc.
Therefore, mid and long-term it seems better to fundamentally separate
the gateway and server API such that each can be implemented specific
for the requirements.
=> separate stateful and stateless server implementation

.github/workflows/go.yml, .github/workflows/release.yml, .github/workflows/vulncheck.yml, client.go, cmd/kes/enclave.go, enclave.go, internal/http/server-enclave-api.go, internal/http/server.go, internal/sys/fs.go, internal/sys/vault-fs.go, internal/sys/vault.go
This commit adds a describe enclave
API: `/v1/enclave/describe`.
In addition, this commit adds a client
API implementation and CLI command for
fetching enclave description.
=> add `/v1/enclave/describe` API

client.go, cmd/kes/key.go, enclave.go, internal/http/gateway-key-api.go, internal/http/gateway.go, internal/http/server-key-api.go, internal/http/server.go, kestest/gateway_test.go, key.go
This commit adds a describe key
API: `/v1/key/describe` to the
stateful/stateless server.
In addition, this commit adds a client
API implementation and CLI command for
fetching a key description.
=> add `/v1/key/describe` API

internal/key/cache.go
This commit fixes a bug in the offline
caching. Before, the `unused` caching time
was used for the offline cache - which is incorrect.
This leads to confusing offline caching behavior.
The offline cache works for some amount of time,
precisely the `unused` time.
This commit fixes this by using the correct `offline` time.
=> cache: fix bug in offline caching

client.go, enclave.go
This commit allows to instantiate new `Enclave`s
to access enclaves within a KES server.
In particular, it is possible to obtain an `Enclave` from a `Client` via:
```
enclave := client.Enclave("my-enclave")
```
Further, it is possible to instantiate new `Enclave`s from scratch via:
```
enclave := kes.NewEnclave("https://127.0.0.1:7373", "my-enclave",
certificate)
```
=> kes: allow clients to instantiate `Enclave`

.github/workflows/go.yml, .github/workflows/release.yml, .github/workflows/vulncheck.yml, client.go, integration_test.go, keserv/config.go, keserv/config_test.go, keserv/env.go, keserv/example_test.go, keserv/testdata/fs.yml, keserv/testdata/invalid_keys.yml, keserv/testdata/invalid_root.yml, keserv/yml.go
This commit fixes two nil assignment bugs
when en/decoding server config structs.
In both cases, an entry used to be assigned
to a potentially nil map causing a panic.
Further, this commit adds some basic tests
for reading / writing server configuration.
=> keserv: fix nil assignment and add tests

client.go, enclave.go, error.go, go.mod, go.sum
Instead of computing memory limits by
hand as `1024 * 1024` or `1<<20` use
human readable constant definitions.
=> use human readable memory limits

internal/vault/vault.go
This commit fixes an bug when connecting
to Hashicorp Vault with AppRole credentials.
Before, ommiting the approle engine in the
config file no default engine path has used.
Now, if the approle engine in the config file
is empty, we default to `approle`.
RELEASE_TAGS BUG_FIX
=> vault: use default approle engine

cmd/kes/gateway.go, cmd/kes/server.go
This commit disallows the use of TLS server
certificates that do not contain any SANs.
Certificate verification fails when a certificate
contains a CN but not a SAN since Go 1.15.
Ref: https://go.dev/doc/go1.15#commonname
We don't reject client certificates without a SAN
since client certificates may not be verified at
all due to the identity verification.
=> cmd: reject server certificates without SANs

kms/kms.go
This commit fixes a recursion bug in the
`Unreachable.Error` and `Unavailable.Error`
methods.
If the underlying error is not `nil` both functions used to recursively call themself until we hit the
goroutine stack size limit and finally causing the program to crash.
=> kms: fix recursion bug in `Error`

cmd/kes/gateway.go, internal/http/tls.go, internal/http/tls_test.go, keserv/config.go, keserv/config_test.go, keserv/testdata/with_tls_ca.yml, keserv/yml.go, server-config.yaml
This commit adds support for custom CA
certificates for verifying mTLS client
certificates.
Now, the stateless KES server accepts
an optional `ca:` config field that points
to a X.509 certificate file or directory
containing X.509 certificate files.
If set, the X.509 certificates get added to
the system root certificate pool.
=> add support for custom CA certificates

keserv/yml.go
This commit fixes a bug when initializing
a GCP secretsmanager.
A typo caused the YAML unmarshaling to use
an AWS SecretsManager not a GCP SecretManager.
=> keserv: fix GCP secretmanager initialization

cmd/kes/update.go, go.mod, go.sum
This commit adds additional options to the `kes update` command:
```
Usage:
kes update [options] [<version>]
Options:
-k, --insecure           Skip TLS certificate validation.
-d, --downgrade          Allow downgrading to a previous version.
-o, --output <file>      Save new binary to a file instead of
replacing the current binary.
--os <OS>            Download a binary for the specified OS.
--arch <arch>        Download a binary for the specified CPU
architecture.
--minisign-key <key> Use the specified minisign public key to
verify the binary signature.
-h, --help               Print command line options.
Examples:
$ kes update
$ kes update v0.21.0
$ kes update -o ./kes-darwin-arm64 --os darwin --arch arm64
```
Now, `kes update` can be used to update/dowgrade the actual KES binary itself …
=> cmd: improve update subcommand

enclave.go
This commit fixes a bug when constructing the URL containg an enclave as query paramater.
Before, the URL API path got overwritten with the URL query parameter. For example:
```
/v1/key/create/my-key?enclacve=my-enclave
```
would have been overwritten to:
```
?enclacve=my-enclave
```
=> enclave: fix bug in enclave name query parameter construction

internal/gcp/config.go, internal/gcp/secret-manager.go
This adds a safety check to the GCP KMS implementation when parsing the GCP credentials.
A YAML string can contain control characters like newlines (`\n`). However, whether they are interpreted as such control characters or as raw symbol sequences (`\` , `n`) depends upon whether the YAML string is single- or double-quoted.
The YAML string `"Hello\nWorld"` is rendered as:
```
Hello
World
```
In contrast, the YAML string `'Hello\nWorld'` is rendered as:
```
Hello\nWorld
```
A GCP private key is will contain newline characters and a user may choose to use single-quotes for the key. Therefore, we replace the symbol sequence (`\` , `n`) with the actual `\n` newline character to avoid GCP SDK parsing errors.
Further, this commit makes the GCP credentials marshaling compliant with: …
=> gcp: avoid passing invalid private keys to SDK

internal/gcp/iterator.go, internal/gcp/secret-manager.go
This commit fixes two bugs in the list key
implementation for GCP SecretManager.
The first bug is caused by a additional `*`
appended to the `ListSecrets` API call.
This caused GCP to respond with an error like:
```
rpc error: code = NotFound desc = Project 'projects/<project-id>/*' not found.
```
Further, the GCP ListSecrets API returns full paths for each secrets. However, KES clients just know about the key name. Therefore, we have to strip the path prefix and just return the path base as key name.
=> gcp: fix bug when listing keys

cmd/kes/metric.go, cmd/kes/status.go
This commit replaces the custom
memory unit formatting with a
package.
Further, this commit fixes a race
condition in the metric command.
=> cmd: replace mem unit formatting

cmd/kes/identity.go, cmd/kes/key.go, cmd/kes/main.go, cmd/kes/policy.go
This commit adds support for KES
enclaves for various commands.
The CLI commands will use the enclave
specified by the `KES_ENCLAVE` env. variable,
or, if not set, uses the default enclave.
Each command also accepts a `-e, --enclave <name>` flag
which overwrites the enclave set via `KES_ENCLAVE`.
=> cmd: add support for enclaves

keserv/config.go
This commit fixes an assignment bug in the AWS
SecretsManager config. This error leads to an
KES server error log message like:
```
aws: failed to create 'my-key': InvalidSignatureException: Credential should be scoped to a valid region.
status code: 400
```
=> keserv: fix region assignment in AWS SecretsManager.

keserv/config.go, keserv/config_test.go, keserv/testdata/invalid_version.yml, keserv/testdata/with_version.yml, keserv/yml.go, server-config.yaml
This commit adds a version field to the
server configuration. It's purpose is to
reliably detect and parse incompatible
server config files in the future.
Currently, the only valid value for the
version field is "v1" and the field itself
is optional - for backward compatibility.
```
version: v1
address: 0.0.0.0:7373
...
```
Future versions of KES will eventually require
this field.
Based on the version field we can now distinguish
incompatible config files and parse or reject them with a proper messaging.
=> keserv: add version field to server config

internal/cli/init.go, internal/cli/init_test.go, internal/cli/testdata/env.yml
This commit requires a init config file
version on stateful KES server config files.
Currently, the only valid version is 'v1'.
=> cli: add version field to init config files

.goreleaser.yml, internal/http/gateway-api.go, internal/http/server-api.go, internal/sys/build.go, kestest/example_test.go
This commit changes the KES CLI and server versioning scheme from
semver to a rolling release model where the server version is the
RFC3339 commit timestamp.
In general, semver is useful for libraries, like the KES SDK, to
signal compatibility and API breaking changes.
However, it is less useful for a server and CLI. Further, the KES
repo contains the SDK as well as the CLI and server code. If, for
example, there would be a breaking change in the SDK but not in the
CLI or server API we still would create a new major release of the
KES server and CLI. Likewise vice-versa.
Hence, we separate the SDK and CLI/server versioning. The SDK continuous
to use semver. However, the CLI and server will use rolling release
versioning.
In particular, the CLI and server version is now the time of the …
=> use commit-time based release tags instead of semver for server

cmd/kes/autocomplete.go, cmd/kes/main.go
This commit adds command and flag auto-completion
for the `kes` command.
Auto completion can be installed via the
```
kes --auto-completion
```
=> cmd: add auto completion for bash and zsh

internal/keystore/vault/vault.go
This commit fixes a bug introduced by `v0.22.0`.
In the config file, a user may specify K8S JWT
as file path containing the actual token.
We stopped reading the JWT token if the user specified a file path.
This commit restores this behavior.
Fixes #318
=> vault: read K8S JWT token from file

client.go, cmd/kes/key.go, cmd/kes/main.go, cmd/kes/secret.go, enclave.go, error.go, internal/http/server-secret-api.go, internal/http/server.go, internal/secret/secret.go, internal/sys/enclave.go, internal/sys/fs.go, internal/sys/secret-fs.go, internal/sys/vault-fs.go, key.go, secret.go, secret_test.go
This commit adds a new set of server APIs, client
APIs and CLI commands for secrets.
A secret is, similar to a crypto. key, an object
stored at the KES server. However, in contrast
to a key, a the value of a secret can be modified
and fetched from the client.
A typical use case for secrets are e.g. passwords
or API keys.
This commit adds five new server APIs:
- `/v1/secret/create`
- `/v1/secret/describe`
- `/v1/secret/read`
- `/v1/secret/delete`
- `/v1/secret/list`
Note that there is currently no modify or edit
API endpoint. Further, a secret can only be
created if no such secret exists. Otherwise,
the KES server returns a `ErrSecretExists` error.
On the client side, this commit adds new SDK
functions (corresponding to the server APIs)
and CLI commands for managing secrets.
For example: …
=> add new secrets API

apikey.go, apikey_test.go, cmd/kes/identity.go, cmd/kes/main.go
This commit adds API keys as secret-based
authentication mechanism.
An API key has the following format:
```
kes:v1:base64-encode(<key-type> | <key-bytes>)
key-type:  1 byte key algorithm identifier
key-bytes: value of the secret key
```
An example API key looks like this:
```
kes:v1:ACQpoGqx3rHHjT938Hfu5hVVQJHZWSqVI2Xp1KlYxFVw
```
Like TLS certificates, an API has a corresponding
identity. The identity of the example API key
above is:
```
0426fa9a04bc2756b92fbe8a97e1a1e07b53ecf04ed33da22c33e5c9faeb8cbb
```
Now, the `kes identity new` and `kes identity of`, by default, generate an API key resp. compute the identity from an API key.
***
Under the hood, an API key deterministically generates a private/public key pair - from which a CA-signed / self-signed certificate can be generated. …
=> add support for API keys

cmd/kes/gateway.go, internal/keystore/kes/kes.go, keserv/config.go, keserv/yml.go, server-config.yaml
This commit adds keystore support for KES.
Now, a stateless KES server can use a stateful
KES server for storing keys as secrets.
The KES server now accepts a new KES keystore
config:
```
kes:
endpoint: 
- ""           # The endpoint (or list of endpoints) to the KES server(s)
enclave: ""    # An optional enclave name. If empty, the default enclave will be used
tls:           # The KES mTLS authentication credentials - i.e. client certificate.
cert: ""     # Path to the TLS client certificate for mTLS authentication
key: ""      # Path to the TLS client private key for mTLS authentication
ca: ""       # Path to one or multiple PEM root CA certificates
```
=> keystore: add support for KES<->KES setup

.github/workflows/go.yml, Dockerfile.release
This commit replaces the UBI-minimal container image with a multi-level docker build for a UBI-micro
container.
This reduces the image size and avoids unneccesary bloat - which may be flagged by security scanners.
A multi-level docker build is necessary because
the UBI-micro image does not contain a package
manager and we need to update the CA certificate
bundle.
=> move from UBI-minimal to UBI-micro containers

cmd/kes/gateway.go, internal/api/api.go, internal/api/enclave.go, internal/api/identity.go, internal/api/key.go, internal/api/log.go, internal/api/metric.go, internal/api/policy.go, internal/api/router.go, internal/api/secret.go, internal/api/status.go, internal/api/version.go, keserv/config.go, keserv/env.go, keserv/example_test.go, keserv/yml.go, server-config.yaml
This commit adds the ability to customize the
KES server API.
Now the KES server config file contains an `api`
section:
```
api:
<api-path>:
skip_auth: bool
timeout:   time.Duration
```
The KES server uses sane defaults for all APIs.
Further, all APIs except `/version` and
`/v1/identity/self/describe` require authentication
by default.
In general, authentication should not be disabled.
Under certain circumstances, disabling authentication
may be an option to simplify the integration of e.g.
monitoring.
At the moment, authentication can only be turned
of for the following APIs:
- `/v1/metrics`
- `/v1/status`
- `/v1/api`
Now, all APIs returned by the `/v1/api` API also
report whether authentication is enabled or disabled.
=> allow server API customization 

.github/workflows/go.yml, .github/workflows/release.yml, internal/keystore/gcp/secret-manager.go
This commit fixes a bug in the GCP SecretsManager
status check implementation.
Commit 64f37b1 changed the status check for a general TCP status check to a keystore specific HTTP status check.
As part of this change, the GCP implementation
only considered the SecretsManager endpoint
provided in the config file - which is usually
not set - and did not fallback to the GCP default: `secretmanager.googleapis.com:443`
This commit fixes this such that it is no longer
required to set the GCP endpoint to successfully
query the SecretsManager liveness.
=> gcp: use default GCP endpoint for status checks

edge/server-config.go
This commit fixes a recursion bug in the iterator
implementation.
=> edge: fix recursion bug in iterator

.golangci.yml, cmd/kes/gateway.go, cmd/kes/identity.go, cmd/kes/key.go, cmd/kes/log.go, cmd/kes/policy.go, cmd/kes/server.go, go.mod, internal/http/retry.go, internal/https/flush.go, internal/keystore/azure/key-vault.go, internal/keystore/gcp/secret-manager.go
This commit adds the staticcheck linter and fixes
the reported staticcheck linter warnings.
The deprecated lint warning (SA1019) is disabled
since we support some legacy features like
`x509.EncryptPEMBlock`.
=> ci: add staticcheck linter

.github/workflows/release.yml, .goreleaser.yml
This commit adds a check to the release process
to ensure that the git tag matches the commit
timestamp.
This ensures that the releases aren't tagged
incorrectly.
=> add git tag check to release process

cmd/kes/gateway.go, edge/server-config-yml.go, internal/api/health.go, internal/api/router.go, kestest/gateway_test.go, server-config.yaml
This commit adds a new API to check the readiness
of a KES edge server.
In general, liveness and readiness may be checked
by a system like Kubernetes to determine whether
a system (i.e. pod) is available and ready to serve
requests.
In general, the liveness probe should report
whether a system is not in a deadlock state.
In particular, it does not indicate whether
a system is "alive".
In contrast, the readiness probe should report
whether a system is ready to handle requests.
For example, if KES cannot reach its backend
keystore its readiness probe should fail since
it will not be able to process (some) requests.
For KES the liveness probe makes no sense at
the moment since it is not a distributed systems
where deadlocks can occur. Hence, it is not
implemented.
To make readiness really …
=> add readiness API

edge/server-config.go
A typo was found to not load the tenant-id correctly from the config file.
The apparent issue is 404 status code with a HTML page
This commit fixes the behavior.
=>  fix: Load Azure KeyVault tenant-id correctly from the config file

edge/server-config-yml.go
This commit enforces that a JWT passed to the
K8S Vault engine does not require contain '/' (or
other OS path seperator).
If the JWT value contains a OS path separator we
treat it as file and read it from disk.
As a sideeffect, we require that a path to a JWT
is absolute. A relative path - e.g. `token` will
not be treated as filepath. Instead, it must be
specified as e.g. `/var/run/secrets/kubernetes.io/serviceaccount/token`.
Fixes #361
=> edge: handle Vault K8S auht JWTs more strictly

edge_test/aws_test.go, edge_test/azure_test.go, edge_test/edge_test.go, edge_test/fortanix_test.go, edge_test/fs_test.go, edge_test/gcp_test.go, edge_test/gemalto_test.go, edge_test/vault_test.go
Purpose of this change is to enable testing of various backend key stores like Azure, GCP, HashiCorp Vault etc. The tests use command like flags e.g. `aws.config`, `azure.config` to get details to connect to the key store. This is done to make the changes generic and so code remains agnostic to addition of new keystores.
Also this way we are making sure all backend key store integrations work just fine and later when integrated with KES server and client making calls throughKES server, there wont be any surprises.
=> Added unit tests for various key stores

kestest/example_test.go, kestest/gateway.go, kestest/gateway_aws_test.go, kestest/gateway_azure_test.go, kestest/gateway_fortanix_test.go, kestest/gateway_fs_test.go, kestest/gateway_gcp_test.go, kestest/gateway_gemalto_test.go, kestest/gateway_test.go, kestest/gateway_vault_test.go
This change enables integration tests with various backend ketystores.
It uses command line flags like `aws.config`, `azure.config` and `vault.config` to provide keystore connection configurations.
=> Enabled for other backend stores

kestest/gateway_aws_test.go, kestest/gateway_azure_test.go, kestest/gateway_fortanix_test.go, kestest/gateway_gcp_test.go, kestest/gateway_gemalto_test.go, kestest/gateway_mem_test.go, kestest/gateway_test.go, kestest/gateway_vault_test.go
This PR adds a cleanup method to make sure each test works in its entirety and there are no left outs.
Also all tests use the same common functions for scenarios like `create`, `import`, `generate`, `encrypt` and `decrypt` etc.
Different kind of tests can be executed using `go test -v -run="<test>"` command.
e.g. `go test -v -run="TestGatewayMem"` or `go test -v -fs.path=./keys -run="TestGatewayFS"`
=> Refactored `kestest` integration tests

internal/keystore/vault/vault.go
The Vault Kubernetes JWT token is already checked and read [here](https://github.com/minio/kes/blob/master/edge/server-config-yml.go#L429). Doing it again in `vault.go` results in an error, because the JWT token is used as file path.
=> fix obsolete vault kubernetes jwt file read

edge/aws_test.go, edge/azure_test.go, edge/edge_test.go, edge/fortanix_test.go, edge/fs_test.go, edge/gcp_test.go, edge/gemalto_test.go, edge/mem_test.go, edge/vault_test.go
Use random secret key names in tests in the form `prefix-seed-counter`. This way keys become randomized yet predictable tests.
Also fixed an issue with vault test where type of store config was wrong.
=> edge: use random secret key names and delete at end of each test

.github/workflows/edge-test.yml, .github/workflows/go.yml, .github/workflows/release.yml
This commit updates the CI and release config to Go 1.20.6
=> ci: update to Go 1.20.6

edge/edge_test.go
Make sure no lints left around post test execution
=> ci: delete all the keys post test

cmd/kes/gateway.go, edge/keycontrol_test.go, edge/server-config-yml.go, edge/server-config.go, internal/keystore/entrust/keycontrol.go, kestest/gateway_azure_test.go, kestest/gateway_entrust_test.go, kestest/gateway_fortanix_test.go, kestest/gateway_fs_test.go, kestest/gateway_gcp_test.go, kestest/gateway_gemalto_test.go, kestest/gateway_mem_test.go, kestest/gateway_vault_test.go, server-config.yaml
This commit adds support for the Entrust KeyControl KMS backend.
Ref: https://www.entrust.com/digital-security/key-management/keycontrol
```
keycontrol:
endpoint: ""     # The KeyControl endpoint - e.g. https://keycontrol.my-org.com
vault_id: ""     # The Vault ID            - e.g. e30497c1-bff7-4e81-beb7-fb35c4b7410c
box_id:   ""     # The Box name or ID      - e.g. tenant-1
credentials:
username: ""   # The username able to access the Vault and Box.
password: ""   # The user password
tls:
ca: ""         # Path to one or multiple PEM-encoded CA certificates for verifying the KeyControl TLS certificate.
```
=> keystore: add support for Entrust KeyControl

cmd/kes/gateway.go, internal/http/retry.go, internal/https/server.go, internal/keystore/cache.go, internal/keystore/vault/client.go, internal/keystore/vault/vault.go
This commit improves the usage of `time.Timer`
esp. within the Vault token renew and re-auth
logic.
It follows some recommendations from:
https://go101.org/article/memory-leaking.html
Ref: Real Memory Leaking Caused by Not Stopping
time.Ticker Values Which Are Not Used Any More
Further, this commit updates the Vault SDK dep
from 1.5 to 1.9.2 and removes some deprecated API
usages.
=> vault: improve usage of `time.Timer`

.github/workflows/edge-test.yml
This fixes the workflow failures while edge test
=> fix: set GOPROXY for self hosted runner

.github/workflows/edge-test.yml
Setting of `GOPATH` is not needed.
=> fix: remove unwanted ENV vars

.github/workflows/edge-test.yml, .github/workflows/go.yml, .github/workflows/release.yml, cmd/kes/gateway.go, internal/https/server.go, internal/keystore/aws/secrets-manager.go, internal/keystore/azure/key-vault.go, internal/keystore/cache.go, internal/keystore/entrust/keycontrol.go, internal/keystore/fortanix/keystore.go, internal/keystore/fs/fs.go, internal/keystore/gcp/secret-manager.go, internal/keystore/gemalto/key-secure.go, internal/keystore/kes/kes.go, internal/keystore/mem/mem.go, internal/keystore/vault/vault.go, kv/store.go
This commit ensures that the cache and keystore
get closed and any background token renewal processes are stopped when the server updates its config.
This fixes a resource leak for keystores that perform background tasks, like Vault, Gemalto, and Entrust.
=> close keystore when reloading config

edge/server-config-yml.go, edge/server-config.go, internal/keystore/vault/client.go, internal/keystore/vault/config.go, internal/keystore/vault/config_test.go, internal/keystore/vault/vault.go, server-config.yaml
This commit adds support for encrypting K/V entries with a specific transit engine key.
**Transit Engine**
The transit engine is Hashicorp Vault's en/decryption engine. Among others, it allows to send a plaintext to an encrypt API endpoint and receive a ciphertext and vice versa.
Ref: https://developer.hashicorp.com/vault/api-docs/secret/transit
Now, users can specify a transit key name in the KES config file. KES will use this key to en/decrypt its key values before storing them on the K/V backend.
However, this does, in general, not improve security since Vault encrypts all data stored on the K/V engine with internally managed keys. Users may specify a transit key if the want/have to control which key is used to encrypt the K/V data.
=> vault: add support for transit-encrypted K/V

cmd/kes/server.go
This commit fixes a regression in how the `kes server` command handles the config file address.
With this commit, the server correctly uses the value from the `--addr` flag, if provided, and otherwise uses the value from the config file.
=> cmd: fix regression on server address handling

internal/keystore/vault/client.go
This commit simplifies the token renewal proccess
by using just the auth method and no token auth
renewal. This is less fragile and works more reliably in case of errors during the renewal process.
=> vault: simplify token renewal process

internal/api/response.go, keystore.go, server.go
Now, the `/v1/status` API will not try fetch the backend keystore status if:
- offline caching is enabled.
- the keystore is considered offline.
The idea here is that if the cache considered the backend keystore as offline then it is unlikely that a `Status` suceeds. Instead, we can directly return unreachable.
Once, the keystore becomes available again, the cache will detect it eventually (on its next health check cycle).
Among other things, this improves pod availability when `/v1/status` is used as (part of) readiness probes. (i.e. MinIO) Such probes are now less likely to time out since `/v1/status` returns immediately.
However, if the backend keystore becomes unavailable and a `/v1/status` request arrives BEFORE the cache detects that the keystore is offline then these requests may …
=> honor offline caching in `/v1/status` API

cmd/kes/server.go
This fixes a bug where kes would try to split and evaluate the listen address, before the config file was read. This caused kes to fail if no `--addr` value was provided.
With this change, the config file is parsed before we try to determine the listen address. If the `--addr` parameter is provided, we override the value from the config as expected.
This fixes #418 .
=> Parse address from config if not provided with '--addr'

server.go
This commit fixes a bug in the KES audit log API.
The server should flush any audit log event to its clients directly. Otherwise, clients may not see
audit events since they may get buffered.
=> kes: flush audit log events to clients

cmd/kes/server.go
With this commit, the server uses the default addr `0.0.0.0:7373` if none is specified on the command line nor within the config file.
=> cmd: server should use default addr if none is specified

internal/keystore/vault/client.go, internal/keystore/vault/config.go, internal/keystore/vault/config_test.go, internal/keystore/vault/vault.go
This commit re-implements token renewal after it
got removed by 13cee22.
Now, the token renewal process works as following:
- If the token is about to expire (max. 10s before expiry) we try to renew the token if renewable.
- If the renewal fails, or the token is not renewable, KES tries to re-authenticate with the configured auth method.
- If re-authenticating also fails, we retry after 3s.
=> vault: implement authentication token renewal

internal/keystore/vault/client.go, internal/keystore/vault/config.go, kesconf/config.go, kesconf/file.go, server-config.yaml
This commit adds support for authenticating within a different namespace compared to the secret engine namespace.
For example, KES should use the AppRole authentication engine within the root namespace to authenticate but then use the K/V and transit engine within a user-specific namespace, like 'foo'. Similarly, KES may authenticate in the namespace 'foo' but use the secret engines in namespace 'bar' or 'foo/bar'. With this change, this use case is now supported.
The special namespace string '/' is treated as alias for the root namespace and causes KES to not send any namespace header for authentication. If the namespace header for root should be set explicitly, use the namespace 'root/'.
=> vault: support authentication in different namespaces

kesconf/file.go
The new TLS config introduced in #414 does not set client CAs. So when enabling mTLS authentication, client requests fail with `tls: failed to verify certificate: x509: certificate signed by unknown authority`.
This PR fixes this by using the root CAs also for authenticating mTLS clients, like before:
https://github.com/minio/kes/blob/9d1b5ad6dbdd963beabfbc91eb1ca0d330d5cd3d/cmd/kes/gateway.go#L526
=> fix: set client CAs for mTLS auth

server-config.yaml
Small edits to `server-config.yaml` to better match web docs style. This makes it easier to include a sample config in the KES docs.
Closes https://github.com/minio/docs/issues/1123
=> Edit sample YAML config for easier importing to web docs

internal/api/api.go, internal/metric/metric.go, server.go, state.go
This Pull Request returns updating latency and counts missing HTTP metrics after refactoring.
This Pull Request fixes #443
=> fix: return updating http metrics

cmd/kes/autocomplete.go
autoload seems to be something specific to zsh, so we want to separate it's installation from the base bash installation
@aead Can you test this on zsh ?
=> seperating zsh and bash autocomplete

internal/keystore/azure/client.go, internal/keystore/azure/key-vault.go
Closing the http response body seems to be forgotten in the Azure KeyVault 
KMS backend. This commit fixes it.
=> azure: Close http response body

internal/keystore/aws/secrets-manager.go, internal/keystore/azure/key-vault.go, internal/keystore/fortanix/keystore.go, internal/keystore/gcp/secret-manager.go, internal/keystore/gemalto/key-secure.go
This commit fixes a TCP conn leak in the AWS, GCP, Fortanix and Gemalto KMS backend. Due to a missing `http.Response.Body.Close` call, the status check in these backends accumulated TCP connections that are not closed by the runtime.
This resource leak can cause OOM issues.
Fixes #445
=> keystore: fix conn leak in {AWS,GCP,Fortanx,Gemalto} backend

internal/keystore/vault/client.go
It looks like vault client overrides error in case if it is returned, and return unhelpful message instead.
This PR adds check if `err` is in fact `nil` before returning custom error.
=> Vault client ignore errors on return

internal/keystore/fortanix/keystore.go, internal/keystore/gemalto/key-secure.go
This commit fixes an issue on the Gemalto and Fortanix status checks. Before, the status check for both backends used the `http.DefaultClient`. This can cause TLS verification issues when the backend uses certificate not issued by one of the server's root CAs - e.g. with a custom root CA.
Now, the status check uses the HTTP client used for other API calls, like creating a key, with a TLS configuration provided to the server.
=> keystore: use pre-configured client for {Gemalto,Fortanix} status check

.github/workflows/go.yml, .github/workflows/release.yml, internal/keystore/vault/vault.go
This commit improves the Vault API interaction by
using the `vaultapi.KVv1` and `vaultapi.KVv2` types where possible. This simplifies the `List`, `Delete` and `Get` APIs.
Further, this commit changes the `List` API implementation by using HTTP GET instead of LIST. This is a workaround that prevents listing errors caused by some middleware/firewalls. Such systems may reject API calls with "non-standard" HTTP methods.
=> vault: improve Vault API interaction

cmd/kes/policy.go
Remove the non-existing `rm` subcommand from the `policy` command.
=> Remove 'rm' from list

cmd/kes/server.go, keystore.go
This commit fixes a bug in the cache configuration logic. As documented in https://github.com/minio/kes/blob/master/server-config.yaml#L147 KES is supposed to apply a default KES configuration when none is provided.
With this commit, a KES server (started via the `kes server` command) applies a default cache config, if none is set. The `kes/kesconf` package does not implement the default configuration since we don't want to modify the user input at this level.
=> set cache default values as documented

.github/workflows/go.yml, .github/workflows/release.yml, cmd/kes/main.go, cmd/kes/migrate.go, go.mod, go.sum, internal/cli/exit.go, internal/crypto/key.go
This commit adds support for migrating keys to minkms via the `kes migrate` command. Migrating all keys
of a KES backend to a MinKMS server can be done as following:
```
kes migrate --from src-config.yml --server 127.0.0.1:7373 --enclave minio --api-key k1:...
```
Currently, this implementation has the following limitations:
- The HMAC key is not migrated. This requires support from MinKMS. However, HMAC keys are not used for S3 object encryption and have been added to KES recently.
- Ciphertexts produced by KES cannot be decrypted auto. because they lack the key version prefix (e.g. 'v1:'). Future KES servers may use ciphertexts with key versions and MinKMS may accept a ciphertext without one.
=> cmd/kes: add support for migrating keys to minkms

cmd/kes/identity.go
Fix the `kes identity new --ip` example so it includes the `--key` and `--cert` options (required).
=> Fix `identity new --ip` example

keystore.go
This commit fixes a goroutine leak that occurs when reloading the server configuration.
During a config reload, the server establishes a 2nd connection to the backend keystore and replaces the existing connection with the newly opened one. The switch is performed atomically (without locking) to not block or abort ongoing requests.
Once the server has replaced the keystore connection, it closes it. Before this commit, the server stopped the in-memory key cache and its GC goroutines. However, it did not close any resources (goroutines/file descriptors) allocated by the replaced keystore. This commit fixes this.
The resource leak can only be observed when reloading the KES server config - i.e. using SIGHUP signals
=> fix goroutine leak when reloading server config

internal/keystore/vault/vault.go
This commit improves the Vault status check logic. KES has to clone the Vault client since it has to clear the namespace header for status checks.
However, KES should use the same TLS client config and token configured on the client when performing such status checks. KES has to opt-in to this behavior since the Vault SDK doesn't do this by default.
=> vault: clone client TLS config and headers for status checks

server-config.yaml
Closes: https://github.com/minio/kes/issues/478
=> fix: remove tab character from example yaml config as it is invalid

internal/keystore/vault/client.go, internal/keystore/vault/vault.go
This commit changes the Vault token renewal logic to renew a token earlier than 10s before it expires. Now, if the token has a TTL > than 1m (or 30s) the token is renewed 1m (or 30s) before it expires.
This commit also adds a `context.Context` to the Vault authentication function.
=> vault: renew token earlier

.github/workflows/go.yml, .github/workflows/release.yml, internal/keystore/vault/vault.go
This commit disables TCP connection reuse for Vault. Apparently, TCP connections to Vault might hang if Vault gets shutdown forcefully.
The downside of this commit is that KES has to re-open a new TCP connection for every interaction with Vault. However, KES should not reach out to Vault most of the time. Hence, this change seems acceptable.
=> vault: do not reuse TCP connections

internal/keystore/vault/client.go
This commit adds a delay that has to ellapse before a new Vault auth. token is used. A dist. Vault cluster may experience some replication lag. Hence, some cluster nodes already have the renewed token while others don't. If KES makes a request to a Vault node that does not have the renewed token, then the Vault node will reject the request.
By waiting a certain amount of time (e.g. 30s) KES allows the Vault cluster to sync a renewed token to all peer nodes. KES cannot know when the token will be replicated but 30s seems a reasonable value for most practical purposes.
=> vault: delay the usage of renewed auth tokens

cmd/kes/identity.go, cmd/kes/key.go, cmd/kes/log.go, cmd/kes/policy.go, internal/keystore/vault/client.go, kesconf/config.go, kesconf/config_test.go
The JWT for authentication to Hashicorp Keyvault is only read during initialization or when `SIGHUP` is received. This results in issues when the SA token expires and the Keyvault client token needs to be refreshed. This PR will re-read the JWT file for every authentication.
Related to https://subnet.min.io/issues/12909.
=> Re-read JWT file for every authentication

cmd/kes/main.go
It looks like `tls.Config.Certificates` will not always send the client certificate.
The Go TLS code contains the following:
```go
func (c *Conn) getClientCertificate(cri *CertificateRequestInfo) (*Certificate, error) {
if c.config.GetClientCertificate != nil {
return c.config.GetClientCertificate(cri)
}
for _, chain := range c.config.Certificates {
if err := cri.SupportsCertificate(&chain); err != nil {
continue
}
return &chain, nil
}
// No acceptable certificate found. Don't send a certificate.
return new(Certificate), nil
}
```
So if the certificate doesn't match the conditions in `cri.SupportsCertificate`, then it won't be sent.
=> Use `GetClientCertificate` to ensure client certificate is sent

internal/keystore/vault/client.go
This commit resets the token TTL to zero once we start another re-authentication attempt. The reason is that if we fail to re-authenticate, we should not wait again for 80% of the prev. token TTL but instead re-authenticate right away.
=> vault: reset token TTL to 0 when renewing token

.github/workflows/go.yml, .github/workflows/release.yml, go.mod, internal/keystore/vault/client.go
This commit fixes a bug in the Vault token renewal. When KES renews its current token `T1` and receives a new token `T2`, KES waits a certain amount of time before using `T2` to account for replication lag between Vault nodes.
Vault tokens are not signed but static secrets. Each Vault node in a dist. cluster needs to know the token before being able to verify it. Without the usage delay described above, KES might send a request to a Vault node that has not received the new token `T2`, yet.
Now, KES must also not wait longer then the remaining TTL of the current token `T1`. Otherwise, `T1` expires BEFORE KES starts using `T2`. This results in auth errors like the following:
```
Error making API request.\n\nURL: GET http://127.0.0.1:8200/v1/kv/data/my-key3\nCode: 403. Errors:\n\n* 2 errors …
```
=> vault: limit token delay to not exceed token TTL

Dockerfile
The current base image was released in March 2024, and contains some vulnerabilities. This pull-request bumps the version in the `Dockerfile` from 9.3 to 9.5.
Overview of vulnerabilities in 9.3: https://catalog.redhat.com/software/containers/ubi9/ubi-micro/615bdf943f6014fa45ae1b58?image=65e0ac6949fc66cfe14185b4&architecture=amd64&container-tabs=security
Current 9.5 image: https://catalog.redhat.com/software/containers/ubi9/ubi-micro/615bdf943f6014fa45ae1b58?image=677fd3a0d6e3ce480e3c5e57&architecture=amd64
=> docker: bump base image to ubi-micro:9.5

internal/keystore/vault/client.go, internal/keystore/vault/vault.go
The namespace was not cleared in this location, meaning errors are logged in Enterprise vault when a namespace is used. We are doing this healthcheck request twice: once in client.CheckStatus and again in Store.Status, maybe we can consolidate these? The Store.Status function was already fixed to clear namespace in a previous change.
=> Bugfix: clear namespace for healthcheck request in CheckStatus

internal/api/request.go, internal/api/response.go
This commit adds a `Version` field to various request and response types that identifies a particular key version in a set of master keys.
=> add `version` field to crypto requests/responses
